### ISSUE TITLE
Change language in card in step 9 that relates to child development

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#1001]
Related to this ticket - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/1000.

Change card in step 9 that reads "Concern about your baby or toddler's development" to instead read "Concern about your child's development."

**Comment by kbottagaro** [comment]
Sorry - I'm not sure why the link isn't working. But yes, this ticket
relates to api#310. The idea is that we're changing baby/toddler to child
and, in conjunction with that, adding Child First as an immediate need.

**Comment by rickyctd** [comment]
Hi @kbottagaro is what is circled in the attached screenshot the only location where this text change needs to occur as requested in this ticket? Thanks so much! 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/130072805/f9fc32f5-7ed1-4e44-9c41-c8f0c2a5e38c)

**Comment by kbottagaro** [comment]
Yes, that's it. Thank you!
