### ISSUE TITLE
Change Required Documents Checklist to Required Key Documents Checklist

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#1003]
Change "Required Documents Checklist" in results to "Required Key Documents Checklist"

**Comment by kbottagaro** [comment]
@Sydney Devine ***@***.***> This is marked as completed, but
the change isn't active. Will this be part of tomorrow's releases?

**Comment by sydney-devine** [comment]
@kbottagaro it's just a copy edit. I'm going to approve for release and we can test in prod.
