### ISSUE TITLE
Research reusable design components - Buttons

### ISSUE THREAD

**Issue by hifilorau** [Gary-Community-Ventures/benefits-calculator#1013]
Research and provide documentation about design components (buttons first) that are being created in different pages and suggest a fix that will allow us to use single classes from a global css file that can be used throughout the app for any design components that are reusable.

**Comment by Mdemenko1** [comment]
[Button research.docx](https://github.com/Gary-Community-Ventures/benefits-calculator/files/15012624/Button.research.docx)
