### ISSUE TITLE
Research hardcoded colorado references in Screener

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1017]
There are references to Colorado in multiple parts of the app. Need to find which are hardcoded values. 

<img width="850" alt="Screenshot 2024-04-16 at 2 32 59 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/17464571/73e71ff3-71b6-4923-a01a-f3219c6956bb">

**Comment by Mdemenko1** [comment]
[CO Research.docx](https://github.com/Gary-Community-Ventures/benefits-calculator/files/15114811/CO.Research.docx)
