### ISSUE TITLE
Research how to serve static files in production 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1038]
The new translation admin UI is implemented using various CSS and JavaScript files through staticfiles.

**Comment by mexi-cano** [comment]
For our scale, Whitenoise appears to be a solid option. Links below to the documentation and SO post in case we run into a similar issue on Digital Ocean.

https://whitenoise.readthedocs.io/en/stable/
https://stackoverflow.com/questions/26829435/collectstatic-command-fails-when-whitenoise-is-enabled
