### ISSUE TITLE
Results page on Stingray is showing unexpected zero results

### ISSUE THREAD

**Issue by laurenbriskin** [Gary-Community-Ventures/benefits-calculator#1047]
Hi @bespinosa01 ,
[Slack thread for reference](https://codethedream.slack.com/archives/C061X2UJHKK/p1714508212730429?thread_ts=1714506011.248689&cid=C061X2UJHKK).

As we discussed, I am not getting the expected outcome on Stingray.

Details:
* I'm using https://stingray-app-8z7io.ondigitalocean.app to do QA
* I'm using these test profiles: https://docs.google.com/spreadsheets/d/1Gh86-zH0_nn8rfbCReXLXSL_fLfd8MvQHY_-u0xbBqM/edit#gid=0
* Using the data in Row 3, I expect to see a number the same as or similar to column V, or $148.
* When I put this data through CO's staging, I get a result that includes SNAP: https://benefits-calculator-staging.herokuapp.com/1d2161c5-a6c4-4533-9b56-b65e2b2bd64c/results/benefits <img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0656b820fe51df6694cc360feef477ff7c475884/colorado%20screeing%20results.png" alt="colorado screeing results.png" />
* I also get a non-zero number when using the SNAP screener (https://www.snapscreener.com/)
* Stingray displays a 0 result (https://stingray-app-8z7io.ondigitalocean.app/5c48bccd-516a-40c2-b2f5-292e40c3dda4/results/benefits). 
*
Can you look into this? Thank you!<img width="1397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13d78da115a15f7af1d1d90eade3ab6d25a3eb59/stingray%20results.png" alt="stingray results.png" />

**Comment by bespinosa01** [comment]
Was a config issue related to FPL limits set on stingray. Was using outdated numbers from 2023 :)
