### ISSUE TITLE
Change path for CCCAP in Adams County & Jefferson County

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#1050]
Make links configurable between counties

**Comment by kbottagaro** [comment]
We want to direct people AWAY from PEAK and to Adams County directly for PEAK results.

KB suggestion:

- we'd probably need to direct Adams residents to the county's CCCAP site [here](https://adcogov.org/colorado-child-care-assistance-program-cccap)  - confirm with Adams County
- Syd & team - assess user experience here - there is a lot of information on that CCCAP page
- "As another option: create a simple page on the backend that directs folks to email or call the eligibility team - not sure how complicated that is from a tech perspective since all our other application links direct to outside resources."

**Comment by kbottagaro** [comment]
@sydney-devine as discussed.

**Comment by sydney-devine** [comment]
@kbottagaro where does the Jeffco link need to go to?

**Comment by kbottagaro** [comment]
@sydney-devine Links to the Jeffco and Adams paper applications are below. English and Spanish versions are available so I've linked to both. Also, remember that we'll need to add some context for users so they know how to submit the paper application. 

Jeffco English: https://www.jeffco.us/DocumentCenter/View/26860/CCAP-Application-Packet--English-PDF?bidId=

Jeffco Spanish: https://www.jeffco.us/DocumentCenter/View/26859/CCAP-Application-Packet--Spanish-PDF?bidId=

Adams English: https://adcogov.org/sites/default/files/2023-08/3-Application_rev7.2023.pdf

Adams Spanish: https://adcogov.org/sites/default/files/2023-08/3-Application_rev7.2023.pdf

**Comment by kbottagaro** [comment]
Ok, thanks.

**Comment by ivonne-hernandez** [comment]
Pair with Caleb on this.

**Comment by kbottagaro** [comment]
Update: Adams is now directing families to an electronic questionnaire instead of the paper application. Questionnaire links are below:

English - https://adcogov.org/forms/ccap-program-enrollment-freeze-waitlist-eng

Spanish - https://adcogov.org/forms/ccap-program-enrollment-freeze-waitlist-esp

**Comment by sydney-devine** [comment]
@ivonne-hernandez @CalebPena ^ can we swap out these links before we release please?

**Comment by kbottagaro** [comment]
Adding to ticket for reference: Jeffco instructions for paper app are as follows:

You should print the application and submit it in one of the following ways:

(1) Scan and email to CCAPCustomerService@co.jefferson.co.us.

(2) Fax to 303-271-4447.

(3) Drop off at The Laramie Building, 3500 Illinois Street, Golden, Colorado 80401. Hours are Monday - Thursday, 7:30am to 5:30pm.

If you receive TANF, ask your career family coordinator for a CCCAP referral.

**Comment by sydney-devine** [comment]
@kbottagaro you'll use the new message feature to just put that up when we release later.

**Comment by kbottagaro** [comment]
ok, thank you
