### ISSUE TITLE
Current code has outdated FPL values. Should strategize keeping current 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1062]
Context: During the debugging of different results between CO staging and stingray. It was pointed out we had 2023 FPL limits configured. Need to strategize best approach moving forward. 

1. Update seed files yearly.

2. During initial conversations it was also pointed out there is an FPL API that could be leveraged.

**Comment by sydney-devine** [comment]
@bespinosa01 - my understanding is that different benefits update their use of different years' FPLs at varying times. . . not sure if that's helpful. We have a ticket for the FPL integration, but the team member who's been looking at that has been swamped and is slowly working through it (it's also a learning/growth task for him).

**Comment by MaxGhenis** [comment]
Echoing @sydney-devine's comment - we model when each program adopts FPL changes (e.g., SNAP will update for 2024 in October). If you see anything that should differ please let us know in https://github.com/policyengine/policyengine-us

**Comment by Linda-Vu** [comment]
Duplicate issue

**Comment by MaxGhenis** [comment]
Duplicate of what?

**Comment by Linda-Vu** [comment]
@bespinosa01 could you link the duplicate issue that you mentioned when we had our discussion today in the comments here? thanks!

sorry about that Max!

**Comment by Linda-Vu** [comment]
@bespinosa01 could you link the duplicate issue that you mentioned when we had our discussion today in the comments here? thanks!

sorry about that Max!

**Comment by bespinosa01** [comment]
@MaxGhenis both this and [Issue-262  (benefits-api)](https://github.com/Gary-Community-Ventures/benefits-api/issues/262) seemed to be trying to solve the same issue. Thanks for that additional context (FPL and SNAP), will keep you posted on the PE side if we find any discrepancies!
