### ISSUE TITLE
2-1-1 Menu accessibility

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#1074]
Rework component to include the header in the tabbing when there is a hamburger menu bar. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/434c2f78-1104-4e07-93ed-dc738062981b)

**Comment by ivonne-hernandez** [comment]
Also fix this spacing issue that occurs with other languages in the 211 version:

<img width="1727" alt="Screenshot 2024-05-20 at 9 46 28 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/0c2389b4-a417-41bd-89e8-da2965bd085f">
<img width="1727" alt="Screenshot 2024-05-20 at 9 46 28 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/0c2389b4-a417-41bd-89e8-da2965bd085f">

**Comment by sydney-devine** [comment]
> Also fix this spacing issue that occurs with other languages in the 211 version:
> 
> <img alt="Screenshot 2024-05-20 at 9 46 28 AM" width="1727" src="https://private-user-images.githubusercontent.com/86989161/332121289-0c2389b4-a417-41bd-89e8-da2965bd085f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjEwMTcsIm5iZiI6MTcxNjIyMDcxNywicGF0aCI6Ii84Njk4OTE2MS8zMzIxMjEyODktMGMyMzg5YjQtYTQxNy00MWJkLTg5ZTgtZGEyOTY1YmQwODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE1NTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMTg2Nzc4ZDM2N2VkODg5ZjFhNGIxYjA3YjU5YTQyMTVmMGQ3MWNhZDVhZTA0ZmZlYThjMjNmYTYyNWYyMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OWsJZrMuMtvQXTb_Z3mUN6Zm5srgZbZyjoEbEklXEC4">

But it's so pretty :P
