### ISSUE TITLE
Create co-branded MFB for FIRC Summit Resource Center

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#1091]
Create a co-branded version of MFB for FIRC Summit Resource Center. Notes:

referrer code: fircsummitresourcecenter

Logo for header

![FIRC Summit County Cobrand](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/e1f4f20c-93b7-4d92-9aca-4b5c6f300c7e)

**KB Notes**
- SD previously created a co-branded button, but FIRC has now decided they want to use a MFB-only logo on their website because their own branding appears in several places on their website. They do, however, want the MFB tool itself to be co-branded once people click on the button. 
- KB has emailed FIRC's logo to SD.
- We'll need to send them a MFB logo they can put on their website. I'll plan to share this one - https://drive.google.com/file/d/1awQowYu_eYgAXnUHXQw9V3HdxgceixW6/view?usp=drive_link.
- The referrer link is https://screener.myfriendben.org/step-1?referrer=fircsummitresourcecenter
- We'll want a data dashboard for this partnership. KB will keep tabs on when the button goes live so we can determine when to create the dashboard.

**Comment by ivonne-hernandez** [comment]
Good morning @sydney-devine Can you please let me know if they just want the orange logo without the MFB text?
