### ISSUE TITLE
Update MFB logos to state specific versions 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1135]
Currently our header and footer are using the standard MFB logo. We have been provided with state specific logos to throw in as replacements.

**Comment by sydney-devine** [comment]
Make sure we use a close-cropped version of the logos  @rickyctd 

@sydney-devine will upload new versions here so we can use them.

**Comment by sydney-devine** [comment]
@rickyctd & @Mdemenko1 here are the logos for this ticket

![CO Logo white (1)](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/08ad3bb0-c584-4ec2-85b0-a718f5dbb48d)

![NC Logo white](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/1e54ec70-0fe4-4f6c-8db2-08e1e4caa2c9)

**Comment by Linda-Vu** [comment]
blocked/on hold for now - need help / research from Brian

**Comment by sydney-devine** [comment]
@Linda-Vu saw there was a PR for this already - can our team help with something? Tagging @CalebPena

**Comment by Linda-Vu** [comment]
@sydney-devine - i'm not sure! i'll let the devs speak to that. @Mdemenko1 & @bespinosa01 is Caleb able to help or do you two need to sit down together first?

**Comment by Linda-Vu** [comment]
@Mdemenko1, wanted to share a suggestion that @CalebPena gave us to help with your `undefined` value!

he said you could pass the config object into the parameters on this function -->
<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--128bcdc8ab0f22498e862de7e12e39255b60bf95/Screenshot%202024-07-26%20at%202.49.08%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 2.49.08 PM.png" />
