### ISSUE TITLE
Remove "Unrelated" as option in Step 5 question "What is this person's relationship to you?"

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#1140]
Remove "Unrelated" as option in Step 5 question "What is this person's relationship to you?"

Background: Proposed changes to Colorado SNAP regs (to be effective as of 8/1/24) reaffirm that a HH is a group of individuals who live together and customarily purchase and prepare food together. The regs will explicitly acknowledge that it's possible for more than one SNAP HH to live together at the same address and will state that each HH sharing an address may apply as a separate HH if they're not mandatory HH members based on familial relationships or financial responsibility. 

MFB data shows that as of 5/17/24, 548 unique screener ids have an ‘unrelated’ household member out of 21,976 unique screener ids that specified having household members (all time) - so 2.5% of screeners and a smaller percentage of individuals representing by those screeners. Removing "Unrelated" will prompt unrelated users sharing housing to complete the tool individually. These people likely purchase food separately and would file taxes separately - so in most respects, they are likely separate households. 

Should only remove this on the frontend from the dropdown and keep the existing field/data stored from previous screeners on the backend.

**Comment by rickyctd** [comment]
@sydney-devine This is no longer adjusted in the code. These frontend options are now in configurations in django, so your team will have to make this edit. (Y'all recently did also give me access, but it's probably better you all do it. But let me know if you'd rather me do it.)

**Comment by sydney-devine** [comment]
> @sydney-devine This is no longer adjusted in the code. These frontend options are now in configurations in django, so your team will have to make this edit. (Y'all recently did also give me access, but it's probably better you all do it. But let me know if you'd rather me do it.)

Oh good to know -  thank you for the heads up!

**Comment by ivonne-hernandez** [comment]
I removed the `unrelated` property from the JSON object in Django admin.
