### ISSUE TITLE
Explore options for optional contact storage

### ISSUE THREAD

**Issue by rickyctd** [Gary-Community-Ventures/benefits-calculator#1152]
Issue: for Step 11, screener asks for optional contact for notifying about new benefits. CO screener hooks this up to HubSpot. We should figure out where the NC screener should hook up to.

Research Goal: Allow user to optionally sign up for new benefit notification.

Possibilities: 
- CTD does also have a hubspot, but it's pretty full and set up specifically for another project.
- Look into sendgrid contact storage for email. (Not sure if this solution also covers phone.)
- If we also want to offer text, we could see about using SIgnalwire. We wouldn't be able to store the contact number in signalwire, however. But Oye team is working on an API, so maybe that's a possibility. We could also stick with email for now and look into SMS later. (Ricky has preference to working with Signalwire/Oye if we need a SMS service because we are already administratively set up for this.)

What we need to know:
- What's the technical feasibility and implementation timeline for each option?

**Brevo vs. Hubspot - Additional questions from Ricky of what we need to know before we can make final decision:**
**- how long would integration take for Brevo vs Hubspot? we're leaning towards Brevo if we can ensure that integration and testing can be completed by mid-September.**
**- Is security/confidentiality as good on Brevo as it is on Hubspot?**
**- How is the customer support quality with Brevo? (Hubspot has very good customer service?)**

Additional context for what GCV workflow looks like: (we do not have to do exactly the same thing)

"We're sending over all of the PII along with some other fields like which of the optional signup option fiolks checked off on optional step. We have hubspot integrated with Sakari for SMS and use that to email and text users if there are new benefits added or if we have another program they might be interested in.
That said, the function built into MFB where people can request copy of their results via sms - that uses twilio directly since that request is running directly from the app. That I'm working through the stupid campaign setup because twilio changed some things and it's trying to get reapproved right now
But hubspot works best for us because the optional opt in for PII also has a consent to contact for other Gary programs in it so we organize users in hubspot that way"

**Comment by mexi-cano** [comment]
### Hubspot 
There are 7 files containing Hubspot business logic. I think it could take us at least a month trying to get a new CRM connected. See screenshot for business logic example. 

<img width="1675" alt="Screenshot 2024-07-16 at 12 42 18 PM" src="https://github.com/user-attachments/assets/e7ff5a0e-09f1-4ff6-bd0e-242e2c1705ac">

### Answers regarding Brevo: 
Brevo scaling: https://www.brevo.com/pricing/
Free tier gives us 300/emails per day. Can scale upwards of 1MM.

For [SMS](https://www.brevo.com/features/sms-marketing/), it handles the messaging compliance for us. Pay-as-you-go messaging.

**Comment by Linda-Vu** [comment]
@mexi-cano &. @bespinosa01 I added some more questions from @rickyctd on the ticket details in bold. let me know if those make sense! hopefully we can get these answers before Wednesday (Ricky's PTO), but if now, we can make a decision together with @hifilorau in Ricky's absence.

**Comment by mexi-cano** [comment]
Brevo (previously Sendinblue) vs. Hubspot - Additional questions from Ricky of what we need to know before we can make final decision:

1. how long would integration take for Brevo vs Hubspot? we're leaning towards Brevo if we can ensure that integration and testing can be completed by mid-September.
I think mid-September is a reasonable outline. See below for the current Hubspot logic.

- `integration.py`
    - Hubspot has no insert or update option in their latest API, so there’s code to first attempt to create a contact. If there is already a contact with a matching email address an exception is thrown. The existing contact id is included in the exception error so we parse the string to grab the id and then do an update call.
        - `upsert_contact`
        - `create_contact`
        - `update_contact`
        - `bulk_update`
        - `get_conflict_contact_id`
        - `mfb_user_to_hubspot_contact`
        - `format_email_new_benefit`
- `views.py`
    - API endpoint that allows users to be viewed or edited.
        - `update` function
        - `upsert_user_to_hubspot`
- `hubspotsync.py`
    - Sync new users to Hubspot and clears PII from local records
        - Error handling
    - MFB allows users to sign up to receive benefits updates or offers. If they do so PII is temporarily stored against their user record. This cron function queries the hubspot, and then clears the PII on the user record in favor of storing the external id. This separates PII from household demographic.
    - For now, we only sync users to hubspot who have signed up for offers or updates and given TCPA consent
        - Check Brevo rate limit (Hubspot rate limit = 100 req per 10 seconds)


2. Is security/confidentiality as good on Brevo as it is on Hubspot?
[Brevo security](https://help.brevo.com/hc/en-us/sections/360000396424-Privacy-and-confidentiality-of-your-personal-information). GDPR compliant. The hosting servers on which Brevo processes and stores its databases are all located within the European Union, on our own servers, on Google Cloud. Advanced security reviews. The engineers in charge of production applications are also controlled each time they access the production environments.

3. How is the customer support quality with Brevo? (Hubspot has very good customer service?)
4.3 / 5 stars on [Trustpilot](https://www.trustpilot.com/review/www.brevo.com). 
Hubspot has 2.7 / 5 on [Trustpilot](https://www.trustpilot.com/review/hubspot.com)
