### ISSUE TITLE
Translation Updates - Somali, Burmese, Nepali & Russian

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#1155]
Documents all attached. 

[Somali.docx](https://github.com/user-attachments/files/15993066/Bug.report.docx)

[My Friend Ben Updated_BU.docx](https://github.com/user-attachments/files/16168280/My.Friend.Ben.Updated_BU.docx)
[My Friend Ben Updated_BU.pdf](https://github.com/user-attachments/files/16168281/My.Friend.Ben.Updated_BU.pdf)
[My Friend Ben Updated_NP.docx](https://github.com/user-attachments/files/16168282/My.Friend.Ben.Updated_NP.docx)
[My Friend Ben Updated_NP.pdf](https://github.com/user-attachments/files/16168283/My.Friend.Ben.Updated_NP.pdf)
[My Friend Ben Updated_RU.docx](https://github.com/user-attachments/files/16168284/My.Friend.Ben.Updated_RU.docx)
[My Friend Ben Updated_RU.pdf](https://github.com/user-attachments/files/16168285/My.Friend.Ben.Updated_RU.pdf)

**Comment by CalebPena** [comment]
- [ ] Somali
- [ ] Burmese
- [ ] Nepali
- [ ] Russian
