### ISSUE TITLE
Research - Add NC Programs 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1156]
**FEDERAL**

- [x] EITC 
- [x] CTC 
- [x] SSI

**Comment by MaxGhenis** [comment]
EITC, CTC, and SSI can inherit from PolicyEngine. We can work together on adding CCDF and TANF to PolicyEngine (mirroring Colorado's approach)/

**Comment by bespinosa01** [comment]
> EITC, CTC, and SSI can inherit from PolicyEngine. We can work together on adding CCDF and TANF to PolicyEngine (mirroring Colorado's approach)/

Thanks for the note @MaxGhenis! Definitely starting on those already in PolicyEngine. So will reach out about CCDF and TANF.

**Comment by Linda-Vu** [comment]
further research is happening here: https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/1195

**Comment by MaxGhenis** [comment]
I'm getting access denied on that

**Comment by Linda-Vu** [comment]
@bespinosa01 @sydney-devine any tips on how make 1195 visible to Max? see thread above^^

Thank you!

**Comment by MaxGhenis** [comment]
Oh it's #1195. Just can't view the zenhub but shouldn't need to.

**Comment by sydney-devine** [comment]
@Linda-Vu for folks who aren't using zenhub, I usually just click the issue name/number when I open it from the zenhub view and then copy the git link. Or should be easy enough to do #1195 << so that it links to github issue.
