### ISSUE TITLE
Some benefits don't meet $300 threshold in FAQ

### ISSUE THREAD

**Issue by MaxGhenis** [Gary-Community-Ventures/benefits-calculator#1157]
https://co.myfriendben.org/faq says:

>MyFriendBen only includes benefits and tax credits with an annual value of at least $300 or more a year.

However, some benefits are lower than that, e.g.:
<img width="1873" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/6076111/8d6d838f-0349-44e5-8534-c4704212a9b0">

https://screener.myfriendben.org/14b0ed4b-d7ee-403b-8110-d98ac9452539/results/benefits

**Comment by sydney-devine** [comment]
Updated FAQ
