### ISSUE TITLE
Config model UI (Research) 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1162]
Our current UI for updating the config JSON is not intuitive. Would be great to research ability to create some sort of admin tool to manipulate available fields and values in JSON. Think similar to translation admin/api

**Comment by msrezaie** [comment]
So there are two approaches to achieving this based on my research. @Linda-Vu @bespinosa01 

1. There are django packages that provides a better view for modifying JSON values in the django admin interface. An example for this is [django-json-widget](https://pypi.org/project/django-json-widget/) which provides a tree view among others that is more intuitive in editing the configuration objects:
![Screenshot 2024-07-25 211359](https://github.com/user-attachments/assets/83390764-8f64-45b7-a981-2ad92ed1e2d2)

2. For this approach similar to the Translations API, separate routes can be added to redirect to custom templates for modifying configuration objects JSON values.

**Comment by CalebPena** [comment]
I think that we should go with the first approach for now because it is significantly faster than adding a new UI. Also, if we add a new UI, that would require a separate UI for each config, which means that we have to update it every time we add something to the config.

**Comment by Linda-Vu** [comment]
@Linda-Vu close this research and create an implementation ticket for Mo
