### ISSUE TITLE
Icon not displaying in Near-Term Benefits (Urgent Needs) 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#1163]
Colorado Screener shows Icons next to Majority (If not all) Near Term benefits. These are editable through urgent needs in django admin 

Note: Locally I am only getting grocery icon.

<img width="1171" alt="Screenshot 2024-07-09 at 2 32 40 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/17464571/73a72dd0-8dcd-469f-a4fa-09066a577c99">

Colorado Screenshot:

https://benefits-calculator-staging.herokuapp.com/fc24b312-f851-41fc-90f5-3f961ba93baf/results/near-term-needs

<img width="1468" alt="Screenshot 2024-07-16 at 2 29 26 PM" src="https://github.com/user-attachments/assets/a00dcbe9-3e55-44fa-aec2-f85d69a7d8b9">

**Comment by myang1010** [comment]
The reason we're not showing the icon correctly is that we're providing the wrong type value for the urgent needs displayed above. The correct type values should be from the following list:
```
  'Food or Groceries',
  'Baby Supplies',
  'Managing housing costs',
  'Behavioral health',
  "Child's development",
  'Family planning',
  'Job resources',
  'Low-cost dental care',
  'Civil legal needs',
```

For example, in the case of "Early Intervention Colorado," the type we provided is "Concern about your baby’s or toddler’s development," which is not a valid type value. We should provide something like "Child's development." Using the correct type value will ensure the result page shows the correct icon.
<img width="1344" alt="icon_shows" src="https://github.com/user-attachments/assets/17ad3c6c-973f-4970-b1e9-a03e53d22c18">

When entering the "type" value, we need to make sure it matches one of the valid types listed above.
