### ISSUE TITLE
Language is not maintained between National, Colorado, and screener

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-calculator#1181]
If I change the language to Spanish on the national site, and then go to the Colorado site, the language changes back to English. Same thing happens when I go to the screener from the Colorado site.

**Comment by sydney-devine** [comment]
@CalebPena - I thought we took the language param out of the url now? There's no way for me to make it just come up Spanish without it there.

**Comment by CalebPena** [comment]
> @CalebPena - I thought we took the language param out of the url now? There's no way for me to make it just come up Spanish without it there.

It looks like it got broken when we added the language options to the config. I just made a [pr](https://github.com/Gary-Community-Ventures/benefits-calculator/pull/1182) to fix it. It should work if you add `/es/` or `/vi/` to the URL (the trailing slash is important).

**Comment by sydney-devine** [comment]
I think those are already in the url I have, but I can double check once this pr releases on Friday.

**Comment by CalebPena** [comment]
> I think those are already in the url I have, but I can double check once this pr releases on Friday.

I think that you will need to add a trailing "/".
