### ISSUE TITLE
Implement Feedback feature

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-calculator#1196]
Using Sofia's designs - see bottom of the thread below - implement a feedback feature.

- Implement feedback icon that opens up a modal when the user clicks on it.
- this feedback icon will be available on all pages of the screener.
- This modal will feature two buttons - Email button and Survey button.
- The text for "email" button and the text for "survey" button should be configurable within Django admin.
- The email button link in the modal needs to be configurable within Django admin so that either GCV and CTD can add their respective emails.
- The survey button link should open a new tab, and this link should also be configurable by GCV and CTD within Django admin.

additional acceptance criteria:
- after the user has selected one of the options in the modal (which opens a new tab), the modal will automatically close
- ensure that the modal never covers the continue button
- ensure that the modal doesn't push the footer down when it's opened
- when the user scrolls, the modal will stay at the bottom where it was opened but will not scroll with the screen

**Comment by Linda-Vu** [comment]
https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/665

**Comment by Linda-Vu** [comment]
@kc-accidental could i get you to add the final design and svg for this ticket when you get a chance? this is based on the research you did a while back on 665 for the feedback feature.

**Comment by kc-accidental** [comment]
Here is the icon- one is a PNG and the other is SVG. Lmk if you need anything else!

![feedback Icon (1)](https://github.com/user-attachments/assets/1a9976b7-68ab-4a5d-adcc-8d4f88c09465)
<img width="48" alt="feedback Icon" src="https://github.com/user-attachments/assets/ac5650d7-8cb3-4e10-8811-295db7464154">

**Comment by Linda-Vu** [comment]
@kc-accidental tysm! could you also attach the final design for what it should look like when the user clicks on this button?

**Comment by kc-accidental** [comment]
> @kc-accidental tysm! could you also attach the final design for what it should look like when the user clicks on this button?

So I'm not sure what it would look like. I did a quick sketch of what I saw for that popup, but it sounded like Sydney and Ricky were considering an existing airtable of some type and I wasn't asked to continue designing that feature.

**Comment by Linda-Vu** [comment]
@kc-accidental so some additional context is that @sydney-devine and Ricky brought this feature up again last week - we're hoping to implement it in a coming sprint! are you able to revisit the design on it?

from the discussion we had, it sounds like we're thinking the button would open up a modal with a contact email and link to a google form. i think the colorado version would have a contact email for them, and NC version would have contact email for us. we also through out the idea of the modal having a link that would take them to a google form. maybe @sydney-devine could chime in about which implementation Sofia could design for?

thanks so much!

**Comment by Linda-Vu** [comment]
pop-up modal with two buttons 

1. email us: at
2. button that links out to a form (conditional url)

**Comment by Linda-Vu** [comment]
@kc-accidental just following up before I go out of town - I showed you the most recent comment right? that's the design Sydney wants to go with. thank you so much!

**Comment by kc-accidental** [comment]
Here is a pop up for both mobile and desktop. Thoughts? <img width="766" alt="Screenshot 2024-08-06 at 1 59 51 PM" src="https://github.com/user-attachments/assets/60cd1604-4dc2-462c-8189-923621c86411">
<img width="240" alt="Screenshot 2024-08-06 at 1 59 41 PM" src="https://github.com/user-attachments/assets/925a43f2-735c-428b-8821-ea2701d883f7">

**Comment by Linda-Vu** [comment]
@kc-accidental lookin' good!! :)
@sydney-devine does this look good to you?

**Comment by sydney-devine** [comment]
@Linda-Vu @kc-accidental this looks great ty!

**Comment by Linda-Vu** [comment]
email details and survey links need to be configurable in django admin
