### ISSUE TITLE
Make CCIG Cobrand / Whitelabel

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#1218]
- [x] referrer code = ccig
- [x] Logo to come
- [x] If a user goes through from this referrer link, skip optional sign-up question.
- [x] Add landing page like JeffCo >> Make sure Get Started off landing page, keeps URL params.
- [x] Results Page: Add additional language (use Let's Get Set model) Something to the effect of Thanks for filling out MyFriendBen. You've completed you're CCIG registration. Review programs that you might be eligible for. . . something. . . @sydney-devine will sharpen this up later.

**Comment by CalebPena** [comment]
@sydney-devine do we want an icon to go with the message? We currently have this for lgs.
![image](https://github.com/user-attachments/assets/fe629cb2-434e-409a-85df-a101ed8d8b68)

**Comment by sydney-devine** [comment]
@CalebPena let's axe the icon and just keep the background and bold text.

**Comment by sydney-devine** [comment]
@CalebPena logos - Vertical one is for the landing page
![CCIG Horizontal MFB Partnership](https://github.com/user-attachments/assets/8b87d786-886e-4554-99d0-35602249746b)
![ccig partnership with mfb vertical](https://github.com/user-attachments/assets/5aed2c1b-d2b5-41f4-a110-0bc9fa1ceda7)

**Comment by CalebPena** [comment]
![image](https://github.com/user-attachments/assets/cbbc234e-be4a-4d61-b3f9-4eab08f71cd2)

**Comment by CalebPena** [comment]
![image](https://github.com/user-attachments/assets/fecfbc4b-352e-4d25-90d4-211548885481)

**Comment by sydney-devine** [comment]
> ![image](https://private-user-images.githubusercontent.com/62856626/357168233-c5191a66-b1f6-4f61-88d9-bf185b5591b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTQwMjMsIm5iZiI6MTcyMzQ5MzcyMywicGF0aCI6Ii82Mjg1NjYyNi8zNTcxNjgyMzMtYzUxOTFhNjYtYjFmNi00ZjYxLTg4ZDktYmYxODViNTU5MWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIwMTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZTNkZjVmNzE5ZjgyZjYwZjg0MGM1ZTBjOGZmZjI0OTY4MDc5N2FkNmVmNzI0MjQxYmRhNjIyOGE2YjdmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E-887ZbTz8hmb8Ldr6w_mKkpYoKgyRgBmBVxPrTdopQ)

Copy: Thank you for completing your application to join the Colorado Community Insight Group by filling out MyFriendBen. Your application will be processed within 2 - 4 days. In the meantime, we encourage you to explore the benefits and resources that may be available to your family listed below. If you have any questions in the meantime, please feel free to email us at [ccig@garycommunity.org](mailto:ccig@garycommunity.org).

**Comment by sydney-devine** [comment]
> @sydney-devine do we want to add CCIG to the referrer source drop down?

Yes please. Colorado Community Insight Group

**Comment by CalebPena** [comment]
![image](https://github.com/user-attachments/assets/19f3ffb0-b2c6-4004-bb9c-77ba9f33ab49)

**Comment by sydney-devine** [comment]
> ![image](https://private-user-images.githubusercontent.com/62856626/357473967-19f3ffb0-b2c6-4004-bb9c-77ba9f33ab49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjM1ODQsIm5iZiI6MTcyMzU2MzI4NCwicGF0aCI6Ii82Mjg1NjYyNi8zNTc0NzM5NjctMTlmM2ZmYjAtYjJjNi00MDA0LWJiOWMtNzdiYTlmMzNhYjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE1MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzdhYzg1OGI4ZTBjOThmZjgyNDBlYmEwOTUxMDM4OThkZTM4YjczYzhjYjBhMmVjYTk0N2RkMDU0OTQ2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6eAHcBE3JVD_sig3gMqEAAyLK2wv5J6nBykgJjOdLA4)

Add like 1.5 rem padding between logo and paragraphs. 

Unbold the copy.

**Comment by CalebPena** [comment]
![image](https://github.com/user-attachments/assets/7a8f4f45-33c3-43ec-a615-d7962aaa1e53)

**Comment by sydney-devine** [comment]
Ugh Let's double the padding between the logo and header? Sorry, being a little nitpicky now. It just seems smooshed right now.

**Comment by CalebPena** [comment]
![image](https://github.com/user-attachments/assets/c512e4fe-2f6b-45c8-92fb-223707bb6d99)

**Comment by sydney-devine** [comment]
> ![image](https://private-user-images.githubusercontent.com/62856626/357485420-c512e4fe-2f6b-45c8-92fb-223707bb6d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjU4MTMsIm5iZiI6MTcyMzU2NTUxMywicGF0aCI6Ii82Mjg1NjYyNi8zNTc0ODU0MjAtYzUxMmU0ZmUtMmY2Yi00NWM4LTkyZmItMjIzNzA3YmI2ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE2MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYjM3MDM3ZmYyY2FlNGU2ZWYxZDk1NjQ5MzUyYmNlNjU2ZTJlNzZmZGE4ODY5MzU3Mzg4YzA1ZWUzYzFlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d7JeuitZgeK--Dmj2V-ffjlOmwK_I5Rj9aTeJZZc77Q)

Looks great ty
