### ISSUE TITLE
Update the API with new values for estimated savings in NC

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-calculator#1260]
update these values:
MIC (Medicaid for Children) - $372/mnth
MXP (Medicaid Expansion - Adults 19-64)- $512/mnth
MAA (Medicaid for the aged) - $1,086/mnth

Technical details:

Estimated Values are currently calculated by `programs/programs/nc/pe/member.py`

```
    child_medicaid_average = 200 * 12  # TODO: NC specific average goes here
    adult_medicaid_average = 310 * 12  # TODO: NC specific average goes here
    aged_medicaid_average = 170 * 12  # TODO: NC specific average goes here
```

Should update that based on updated values provided by Louise above

**Comment by bespinosa01** [comment]
Need to update estimated savings values for medicaid by type of beneficiary: 

MAD/HCWD/SSI (Medicaid for the disabled)        $18,227/yr - $1,519/mnth
MAA (Medicaid for the aged)        $13,035/yr - $1,086/mnth
MAF (Medicaid for Families With Dependent Children)        $6,146/yr - $512/mnth
MIC (Medicaid for Children)        $4,464/ye - $372/mnth
MPW (Medicaid for Pregnant Women)        $12,536/yr - $1,045/mnth
EM for L&D or cost of service (Emergency medicaid for labor and delivery) $6,268/yr - $522/mnth
MXP (Medicaid Expansion - Adults 19-64 income under 138% FPL)        $6,146/yr - $512/mnth

**Comment by Linda-Vu** [comment]
will point this after we find out how CO handles the classifications
