### ISSUE TITLE
Change MFB to collect MM/YYYY instead of Age

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#1279]
Month - Drop-down
Year - Open field. Limit to numbers

"Please enter your month and year of birth"
"Please enter their month and year of birth"

**Comment by CalebPena** [comment]
Resources on DOB entry:
https://blog.designary.com/p/ux-tip-17-use-text-fields-for-date
https://designsystem.digital.gov/patterns/create-a-user-profile/date-of-birth/
