### ISSUE TITLE
Add HOA fees/ homeowners' insurance & property taxes to expense dropdown menu and include as shelter expenses for SNAP purposes

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#1319]
This ticket has 2 tasks:

- Add the following items to expenses (if possible, add right beneath Mortgage):

Property Taxes
Homeowners or Condo Association Fees & Dues 
Homeowners Insurance

- Include these new expenses in shelter costs sent to PE for purposes of calculating SNAP. (As per Caleb, PE has variables we can use.)

**Comment by sydney-devine** [comment]
@kbottagaro we have these lists showing in order of most used so the most common stuff is at the top. Do we have to place this in a specific spot?

**Comment by kbottagaro** [comment]
I recommend including these additional items right below Mortgage because
they're expenses that a homeowner would incur. We can't really test how
many users input these expenses until we add them.
