### ISSUE TITLE
Add Swahili as language to screener

### ISSUE THREAD

**Issue by rickyctd** [Gary-Community-Ventures/benefits-calculator#1337]
Issue: A CBO working with communities who'd be using screener in NC is advocating for inclusion of Swahili as language support.

Goal: Peer or professionally reviewed Swahili support is made available to users. 

Minimum Acceptance Criteria:
- Option for Swahili is available in external facing screener as part of Step 1 and in upper right corner language selector.
- Translation API in Django supports google translate for Swahili
- Translation is checked by Swahili native speaker and/or translator
- Other relevant adjustments needed for inclusion of Swahili available as language support

**Comment by sydney-devine** [comment]
@rickyctd fyi - @CalebPena is going to finalize the person who will be doing the human check this weekend to see if they're able to do it. Then we have a hopefully quick contracting process with the individual for their time and we can move this forward.
