### ISSUE TITLE
Add ability for document bullets on a program to render a link

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-calculator#1343]
this would require new/improved functionality on Django admin

current behavior -  when a user is on the more info page of a benefit program they can see navigators relevant to the application process of that program, as well as a bulleted list of "required documents" that the application will need from them. in django admin, we can add new documents to the list and change the text of the list, but nothing more.

desired behavior -  the bulleted list of "required documents" should be configurable in django admin to be not only text, but also clickable links for the user.

**Comment by kbrey** [comment]
@rickyctd @bespinosa01 Here's what I have as we discussed, with the link at the end of the document bullet. I threw in examples from the staging app. Let me know your thoughts!

<img width="1718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61e7e09d601693ef3cfc0d4da99d1b3dcb96973c/Screenshot%202024-10-29%20at%204.24.34%E2%80%AFPM.png" alt="Screenshot 2024-10-29 at 4.24.34 PM.png" />
<img width="1706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ef8a8ccab8792fc80747fae3832ec72d14d1373/Screenshot%202024-10-30%20at%2011.47.10%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 11.47.10 AM.png" />
