### ISSUE TITLE
Step 4 - Household member amount not updating correctly

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-calculator#1345]
When a user has filled out the screener with multiple family members, but goes back to change that they only have one family member in their household, the old data persists.

Expected behavior would be that the data gets updated properly and the "cards" displaying household should be updated accordingly. i.e. if the household was initially 2 members (head of household + child) but they go back and indicate that they only have one household member, the screener should get rid of the "card" for the child, keeping only the card for head of household.

Technical notes -
@bespinosa01, @kbrey, @CalebPena, @msrezaie if possible could I get y'all to flesh out details or hints here about what the dev picking this ticket up should think about? Not sure if we are currently prop drilling in the frontend code or if we have a more robust library/approach for global state management in the frontend and how that answer might affect the solution here.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE53Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ab92aa8ae02ce407adf0cd519ec28002c55e976/Screenshot%202024-10-24%20120243.png" alt="Screenshot 2024-10-24 120243.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGR3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--053b40921cb8b8b7ef01f5d3813b798072a80566/Screenshot%202024-10-24%20115848%20%281%29.png" alt="Screenshot 2024-10-24 115848 (1).png" />

**Comment by CalebPena** [comment]
You can truncate the household members array when the household size is submitted.

The following will set the `householdSize`, and truncate the `householdData` array. 
```ts
setFormData({
  ...formData,
  householdSize: newSize,
  householdData: formData.householdData.slice(0, newSize),
});
```

Household size is set in https://github.com/Gary-Community-Ventures/benefits-calculator/blob/main/src/Components/Steps/HouseholdSize.tsx
