### ISSUE TITLE
NC-Specific MFB Logo

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-calculator#1367]
NC users should see an NC specific version of the MFB logo rendered in the navigation bar.

Links to logos here: https://drive.google.com/drive/folders/1ALirUUz8jh0j9nmCLsaamJHipDDOz3NR

These are the NC specific logos once you open the google drive link above ^
![Screenshot 2024-11-13 at 2 08 35 PM](https://github.com/user-attachments/assets/a361dbb7-3f35-415d-b6fe-b2fe29fa0e9d)

**Comment by Linda-Vu** [comment]
@kc-accidental do we have this NC version of the logo available already? thank you!

colorado's version for reference - <img width="1397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEswQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--309c6edd9b2761534354773fef6f372f03f1d855/Screenshot%202024-11-12%20at%205.32.50%E2%80%AFPM.png" alt="Screenshot 2024-11-12 at 5.32.50 PM.png" />

**Comment by kc-accidental** [comment]
> @kc-accidental do we have this NC version of the logo available already? thank you!
> 
> colorado's version for reference - <img alt="Screenshot 2024-11-12 at 5.32.50 PM.png" width="1397" src="https://camo.githubusercontent.com/b68f9160ed0f28582a9e8f9f3545e2d34aa066bdfc55bb9d419074d6051d0de5/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424f457377516e633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d333039633665646439623237363135333433353437373366656636663337326630336631643835352f53637265656e73686f74253230323032342d31312d31322532306174253230352e33322e3530254532253830254146504d2e706e67">

Looks like the image to the screenshot is broken

**Comment by kc-accidental** [comment]
<img width="249" alt="Screenshot 2024-11-13 at 11 40 43 AM" src="https://github.com/user-attachments/assets/126709fb-df0e-47d8-9f53-5a99da9d0356">
@Linda-Vu if you mean this logo- no, I don't have the NC version of it.

**Comment by Linda-Vu** [comment]
@kc-accidental yep, that's the logo i mean! sorry about the wonky screenshot. could you put it on your to-do list to create a north carolina one? thank you so much! i'm not sure about priority level on this, lemme talk to Ricky and get back to you.

**Comment by kc-accidental** [comment]
![Frame 227](https://github.com/user-attachments/assets/ff0f1dcf-f51c-4a17-a156-27242958177c)
![Frame 227](https://github.com/user-attachments/assets/4fe76328-a048-44fd-b922-8aa26e24bb07)
Lulz I just saw this but had already made it anyway. I'm submitting it just in case!
