### ISSUE TITLE
Update loading spinner

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#659]
[MFB - Animated Gif.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc0c8a974ab2dbc71faa510d8e166ea0cf0f743d/MFB%20-%20Animated%20Gif.zip)

**Comment by CalebPena** [comment]
Created instructions in https://github.com/Gary-Community-Ventures/benefits-api/issues/178
