### ISSUE TITLE
Add a SaSS feedback button - Research best one

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#665]
Give feedback button on bottom right. BH says we buy this and plug & play. Figure out best one to use

Note for Sydney: Bull horn report an issue icon? 

Design Task:
- What would bullhorn icon look like in the app (web & mobile) 
- Frame out functionality - pop-up window? - when someone clicks on it to report an issue

* Has anyone used one that we can plug & play for this?

**Comment by kc-accidental** [comment]
<img width="1577" alt="Screenshot 2024-01-29 at 2 57 44 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/89f1899c-43a9-4eb8-8aff-baed8a99c2a1">
<img width="1149" alt="Screenshot 2024-01-29 at 2 58 02 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/0320254f-ffdb-434c-8fdf-d414bc1cff65">

Some ideas for the icon on the bottom right of both mobile and website. Feedback welcomed (obvi)!

**Comment by sydney-devine** [comment]
> <img alt="Screenshot 2024-01-29 at 2 57 44 PM" width="1577" src="https://private-user-images.githubusercontent.com/149400219/300602154-89f1899c-43a9-4eb8-8aff-baed8a99c2a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzkwNzUsIm5iZiI6MTcwNjYzODc3NSwicGF0aCI6Ii8xNDk0MDAyMTkvMzAwNjAyMTU0LTg5ZjE4OTljLTQzYTktNGViOC04YWZmLWJhZWQ4YTk5YzJhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxODE5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjMyNWNhN2ZjOWRmMTdmODRmZTFkMTFjZjVjOTJhNGEwMGYxODNhN2ZjNDk3MGQ2ZTJhYmQ4NDNkZTU2M2I4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WXESO-Qdu0OMsj_KKoJ_iQwsHuK_6LHUhJ0adiFhRnw"> <img alt="Screenshot 2024-01-29 at 2 58 02 PM" width="1149" src="https://private-user-images.githubusercontent.com/149400219/300602146-0320254f-ffdb-434c-8fdf-d414bc1cff65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzkwNzUsIm5iZiI6MTcwNjYzODc3NSwicGF0aCI6Ii8xNDk0MDAyMTkvMzAwNjAyMTQ2LTAzMjAyNTRmLWZmZGItNDM0Yy04ZmRmLWQ0MTRiYzFjZmY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxODE5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWU4NzA3MDA0ODZlNjYzZjJiZWNjNDhjYjYzYTY2NWZkYzZkNmUwNWVhYjRmMjMyODg3YTk5NTc5MzhhZTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vE_GxDtLsc8vY5WtD7eyvdQ4nJNejf8kYx8vrcd_Ma0">
> Some ideas for the icon on the bottom right of both mobile and website. Feedback welcomed (obvi)!

I personally like the bullhorn icon best and the orange coloring I think stands out the most. I wonder if it would look a little better if the button was a circle instead of a square, esp on mobile? 

@rickyctd thoughts?

**Comment by rickyctd** [comment]
agreed on orange. I'm not sure that bullhorn communicates what we want? I feels more like an announcement or alert. I think I like the plus sign or star with speech bubble. Also depends on how we want it to do, I feel like that sort of icon/placement is usually associated with a chatbot or live help somehow. There are tools that do that, one that I am aware of is drift, but it is very pricey like this: https://start.drift.com/login

**Comment by sydney-devine** [comment]
> agreed on orange. I'm not sure that bullhorn communicates what we want? I feels more like an announcement or alert. I think I like the plus sign or star with speech bubble. Also depends on how we want it to do, I feel like that sort of icon/placement is usually associated with a chatbot or live help somehow. There are tools that do that, one that I am aware of is drift, but it is very pricey like this: https://start.drift.com/login

I was thinking bullhorn as you could use it to communicate if something is wrong with the app to the email address, but def open to doing the speech bubble. . . definitely don't wanna go chatbot route for capacity and pricing reasons.

**Comment by rickyctd** [comment]
A quick google image search for "report issue icon" got most results being an exclamation point within a shape. I do kind of like a speech bubble with an exclamation point, maybe not in red tho. I've also see some with a flag for issue reporting, and I see a few of those on here as well. What are your thoughts? 
![Uploading Screenshot 2024-01-30 at 4.44.22 PM.png…]()

**Comment by kc-accidental** [comment]
<img width="1555" alt="Screenshot 2024-01-31 at 12 56 22 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/3b86b8ee-cce4-4dd1-8925-39fafe86aaf4">
<img width="709" alt="Screenshot 2024-01-31 at 12 56 52 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/548812dd-8610-4918-bd14-6089615ab291">
Here are the updated icons for mobile and desktop.

**Comment by kc-accidental** [comment]
![Untitled_Artwork 42](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/3d6ec8ac-c483-473e-8cb5-f1933fba0d35)

Here are some ideas for a feedback pop up - I wasn't sure what you guys wanted but I thought I'd throw some ideas to you - maybe spark some ideas.
Added the typical feedback tab as well!

**Comment by kc-accidental** [comment]
> A quick google image search for "report issue icon" got most results being an exclamation point within a shape. I do kind of like a speech bubble with an exclamation point, maybe not in red tho. I've also see some with a flag for issue reporting, and I see a few of those on here as well. What are your thoughts? 

<img width="91" alt="Screenshot 2024-01-31 at 1 11 50 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/48cc06f4-4a78-42b2-993b-96f61dc980f9">

Here's an icon like you were describing!

**Comment by sydney-devine** [comment]
> > A quick google image search for "report issue icon" got most results being an exclamation point within a shape. I do kind of like a speech bubble with an exclamation point, maybe not in red tho. I've also see some with a flag for issue reporting, and I see a few of those on here as well. What are your thoughts?
> 
> <img alt="Screenshot 2024-01-31 at 1 11 50 PM" width="91" src="https://private-user-images.githubusercontent.com/149400219/301278574-48cc06f4-4a78-42b2-993b-96f61dc980f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTUxNTQsIm5iZiI6MTcwNjgxNDg1NCwicGF0aCI6Ii8xNDk0MDAyMTkvMzAxMjc4NTc0LTQ4Y2MwNmY0LTRhNzgtNDJiMi05OTNiLTk2ZjYxZGM5ODBmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxOTE0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWI2Y2ZmY2IxZDE5MDYzZjBjNDE5OWY5NzcyMzhiYzg3MTk2M2VlOGI1OWJiMTA4N2Q1MjQ2ZGRjMjljZjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b7h-HAOtOIz-Msl_QgKMfWTq-L9GCXpfshODj2fgFO8">
> Here's an icon like you were describing!

I like that icon a lot. I can have our designer mock up a version - probably make the exclamation point a little smaller so it isn't that close to the edging.

Regarding the actual pop-up - @rickyctd 0 rush but wanted to circle back on what the airtable version looks like that you guys have used on other projects?
