### ISSUE TITLE
As a user, I would like to see what language availability is on benefits/immediate needs pathways

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#666]
On benefit page, for the get help applying box, design "Preferred Language Available" or "Preferred Language Unavailable" for phone/website. 

Reality, "Preferred Language" should say the actual language: ex: Spanish Available

https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/screen/2341183d-f7d8-4568-8ec9-32c96d71b5c3?fullscreen

**Comment by sydney-devine** [comment]
Add phone and website language availability fields in django, update front end to indicate with website and phone whether preferred langauge is available. e.g. "Spanish Available" in parenthesis, or "Spanish Unavailable" if preferred language is not available  - do this for benefits too. Mock up what links will look like

**Comment by kc-accidental** [comment]
@sydney-devine would the "get help applying" be a different page or a pop up? And if it's already designed, can I see it?

**Comment by sydney-devine** [comment]
> @sydney-devine would the "get help applying" be a different page or a pop up? And if it's already designed, can I see it?

The "Get Help Applying" is a box on the program page. See link above - it should take you to the wireframe

**Comment by kc-accidental** [comment]
> > @sydney-devine would the "get help applying" be a different page or a pop up? And if it's already designed, can I see it?
> 
> The "Get Help Applying" is a box on the program page. See link above - it should take you to the wireframe

Oh I meant when the user clicks/taps on it since it's not clickable on the wireframe.

**Comment by sydney-devine** [comment]
> > > @sydney-devine would the "get help applying" be a different page or a pop up? And if it's already designed, can I see it?
> > 
> > 
> > The "Get Help Applying" is a box on the program page. See link above - it should take you to the wireframe
> 
> Oh I meant when the user clicks/taps on it since it's not clickable on the wireframe.

Ahh sorry for the confusion. The only clickable piece on there is going to be the "Visit Website" link and that will open in a new tab to the navigator's (external) website. Otherwise, that data will just display as shown.

**Comment by kc-accidental** [comment]
@sydney-devine Oh ok, I think the language availability would be best suited for the website the user goes to once they click the link- otherwise, it's not necessary for the MFB app/website since there's already a choose language option available. Unless I'm misunderstanding you?

**Comment by sydney-devine** [comment]
> @sydney-devine Oh ok, I think the language availability would be best suited for the website the user goes to once they click the link- otherwise, it's not necessary for the MFB app/website since there's already a choose language option available. Unless I'm misunderstanding you?

So the context here is that a user selects a language on MFB, but when they click into the actual benefit and see navigator options, we want to be able to flag if the navigator has Spanish speakers on hand or is able to handle Spanish over the phone or in person. Saves families a step vs going to the navigator and realizing they don't have their language option.

**Comment by kc-accidental** [comment]
> So the context here is that a user selects a language on MFB, but when they click into the actual benefit and see navigator options, we want to be able to flag if the navigator has Spanish speakers on hand or is able to handle Spanish over the phone or in person. Saves families a step vs going to the navigator and realizing they don't have their language option.

Ohhh ok, I understand now. 
Here are some thoughts:

I felt a button look would be better for getting help - The button name doesn't need to be lengthy so it could be - assistance, get assistance, get help, application help, etc. -- no more than 2 words.

I'm not sure if the design team you guys worked with created a design system with a secondary button, but the button shouldn't be the same color as the CTA apply online button - if it is, it'll make the CTA blend in with the rest of the page and take away its level of importance. 
If a secondary button hasn't been designed (branding PDF only showed primary and hover colors), the blue outline/white fill would work best for this one.
If we used the gold button, it would be too much ((and I actually feel the two buttons on the top should be the same as the get help button to draw the eye more to the estimates and apply online button and bring more cohesion to the page.))

Earlier I collaborated with the CTD dev team/Ricky and we came up with the 2nd option (one used in the screen shot) for the language availability. 

<img width="969" alt="Screenshot 2024-02-07 at 2 50 22 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/111ccbb7-99aa-47e2-bb27-3c086742055b">

Thoughts?

**Comment by kc-accidental** [comment]
That makes sense-sorry for the confusion!! Here's what you described:

<img width="262" alt="Screen Shot 2024-02-08 at 1 38 26 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/ac8ae188-09f3-429f-a078-ae4f361e9427">

**Comment by sydney-devine** [comment]
@kc-accidental sorry finally closing this one out. I'm going to put this into the backlog to actually get done.
