### ISSUE TITLE
Colorado Coalition for the Homeless White Label

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#672]
White Label for Colorado Coalition for the Homeless

- Add Colorado Coalition for the Homeless to the referrer dropdown
- cobrand logo

![CCH Horizontal Cobrand](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/eec476f1-a2b2-4699-9feb-3e634d9fe6b0)

- need referrer link when complete

**Comment by sydney-devine** [comment]
@ivonne-hernandez Can we swap horizontal header image for this pls? 

![CCH Horizontal Cobrand](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/887638a5-d6a6-4714-b2de-1d028315bc4f)

**Comment by ivonne-hernandez** [comment]
Let me know if this works:

`Desktop`:
<img width="1477" alt="Screenshot 2023-11-09 at 12 00 09 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/c91ab4f5-3ea6-443c-872a-6b542e73181c">
`Mobile`:
<img width="574" alt="Screenshot 2023-11-09 at 12 00 25 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/df5b2f73-0178-41ab-a4b7-1b2275b301b7">

**Comment by sydney-devine** [comment]
@ivonne-hernandez That looks so much better. Thank you!!
