### ISSUE TITLE
As a user, I would like  the apply with navigation portion to show if Spanish is an available language for that navigator

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#683]
https://docs.google.com/spreadsheets/d/1r8oIfRVldFr1scj3uSlE3-O9k1BlORqGYkc5liK8QjY/edit#gid=0

Add front-end so that users can see if Spanish is available 

Check for accessibility

![image](https://github.com/user-attachments/assets/9adea392-4e7c-4200-b0f2-7270b0f4ba79)

![image](https://github.com/user-attachments/assets/dd4efe20-d8ed-4f4a-876b-e4bd9e29e8c6)

**Comment by ivonne-hernandez** [comment]
Only show a flag if they do have Spanish available.
