### ISSUE TITLE
Update "Back" and "Continue" buttons

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#686]
Float "back" button left
Float "Continue" button right

**Back button:**

- capitalized, text in Open Sans with a "<" before it
- Font Color: Mid Blue #41528C

**Continue Button:** 
- Capitalized, text in Open Sans
- Font Color: #FFFFFF
- Background Color: Deep Blue: #293457
- 2 px stroke in black #000000
- HOVER: Font Color: #293457 | Background Color: #ECDEED

**Comment by myang1010** [comment]
Hi @sydney-devine and @bespinosa01, 

I've got a few questions about this ticket,
1. Do we intend to specify a background color for the "Back" button as well? In the screenshot below, applying the Mid Blue color will result in low contrast between the text and background, which may not be user-friendly.

2. After moving the "Back" button to the left and the "Continue" button to the right, they appear quite distant from each other. This might be less convenient compared to their previous positioning.

3. Regarding the `2px stroke in black #000000` under the `Continue Button`, is this intended for the border? Could you please confirm?

The screenshot below provides an overview of the current appearance of the Back button, the Continue button on hover, and the spacing between these two buttons. 

<img width="1326" alt="Screenshot 2023-11-21 at 10 17 04 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/0ea7bf2c-e38c-46a0-b201-d352ebc959db">

Thanks.

**Comment by sydney-devine** [comment]
@myang1010 responded in Slack while I was running around. Lmk if you need more info on this.
