### ISSUE TITLE
 Add "Let's Get Started" - new element templated into questions (Step 2)

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#688]
See Step 2 of comps
Heading should be in deep blue
Roboto Slab

**Comment by ivonne-hernandez** [comment]
@sydney-devine Can you please provide the comps?

**Comment by ivonne-hernandez** [comment]
Duplicate ticket. Per Sydney see this PR: https://github.com/Gary-Community-Ventures/benefits-calculator/pull/764

<img width="1023" alt="Screenshot 2023-11-28 at 4 44 46 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/ab9afbc3-a12e-42b1-8223-4e47c72ced32">

**Comment by sydney-devine** [comment]
@ivonne-hernandez I'm gonna close this out then.
