### ISSUE TITLE
Branding Updates: Confirmation page 

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#693]
- Typography #734 
- Move the edit edit icons to the top right
- Separate out each section with padding. Section background is light lavender #FBF9FC

**Icons**

New Edit Icon
![MFB-app-icons_v3_Edit](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/9cd32c9e-a15b-4943-8640-e8747ab62f28)

Residence Information
![MFB-app-icons_v3_Residence Info](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/ba7ac332-28b8-402d-b6aa-a7ee17a7e1d7)

Household Insurance
![MFB-app-icons_v3_Summary Insurance](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/7aaefcd0-a67b-4709-81a3-b52d8513f62f)

Household Members
![MFB-app-icons_v3_Summary Household](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/affaa758-3e96-4294-a370-ef429663f958)

Head of Household / individual household members
![MFB-app-icons_v3_Summary Head](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/8086f908-10da-4210-9235-6ff82c583569)

Monthly household expenses
![MFB-app-icons_v3_Summary Expenses](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/e99ed52f-f0ef-41a7-bb0f-25807184ed06)

Household Resources
![MFB-app-icons_v3_Summary Resources](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/bd195c51-bc1b-4fc7-9ebc-e39f04f5df4b)

Current household benefits
![MFB-app-icons_v3_Summary Benefits](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/ff45f549-bd2a-4c90-9bc9-c1b5ea702e36)

Immediate Needs
![MFB-app-icons_v3_Summary Immediate](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/863ff70a-6f75-430d-8685-7c5b82d88bf7)

Referral source

![MFB-app-icons_v3_Summary Referral](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/ba86dab3-e6d7-4c5e-b723-74d8576c8f25)

**Comment by mexi-cano** [comment]
I'm unable to download these icons. The workaround I found seems to reduce their quality. Could you please send me the full-res versions? @sydney-devine

**Comment by sydney-devine** [comment]
@mexi-cano Slacking you
