### ISSUE TITLE
Add checkbox to question that asks about HH members (e.g., pregnant, etc.)

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#702]
"Any medical or developmental condition that has lasted, or is expected to last, more than 12 months"
In connection with adding the Medicaid buy-in programs (in this ticket), we should add a checkbox to the question that asks about HH members (e.g., pregnant, etc.). This should read:

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena There's a period at the end of this phrase in the Spanish version - should be deleted (for both user and other HH members). Otherwise looks good on computer and mobile.

**Comment by sydney-devine** [comment]
@CalebPena I removed the period from admin portal.
