### ISSUE TITLE
Child Care, Youth, and Education Lump Sum Value - remove Pell Grant & My Spark from the lump amount

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#704]
Only cap for: UPK, DPP, Head Start + CCCAP ($8,640)
Separate values add to $8,640 total: Pell Grant & My Spark

Verify that this updates the header value

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdec17d836ef245f7afc3cffa1c93c941d880913/image.png)

**Comment by ivonne-hernandez** [comment]
@sydney-devine I have a question in regards to what programs we want to cap. In particular CCCAP falls under child care, not preschool. As such do we want to just cap the following preschool programs:
UPK  - Universal Pre K
DPP - Denver Preschool Program
CO Head Start

These programs should NOT be capped:
CCCAP - Colorado child care assistance program
Pell Grant
My Spark
My Denver Card

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Are we capping UPK, DPP, Head Start, & CCCAP at $8640? Running a staging test, and it appears UPK is not part of the cap.

**Comment by CalebPena** [comment]
Should be fixed. The `name_abbreviated` is case sensitive.
