### ISSUE TITLE
Update "French" language selection. 

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#712]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d17a6c2b07577939873ddde6792859c4e75fd52d/image.png)

It should be "Français"

**Comment by kbottagaro** [comment]
looks good
