### ISSUE TITLE
Create White Label for Let's Get Set

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#718]
- Add Let's Get Set to referral drop-down
- Cobranded logo
-

**Comment by kbottagaro** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTY0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99c4e5945d96ef40cc345298b9b2cde5aafc40fe/Logomark%402x.png)

**Comment by kbottagaro** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekM0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9cf0d9044d3c4305758822a4be988468d888998/Copy%20of%20Full-Logo%402x%20%281%29.png)
