### ISSUE TITLE
As a user going to the results page from Let's Get Set, I would like a route on the results page to provide additional information to the screener to get additional benefits/improve accuracy

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#720]
Users will be taken directly to results page; we'd like a path where they can opt to provide additional data to thereby build out additional benefits in their results

- Light lavender background
- Triangle exclamation point? 

Copy
The following benefits estimates are based limited information from your tax return. If you would like to provide additional information to screen for more benefits and improve accuracy, click here.

**Comment by sydney-devine** [comment]
@CalebPena UPDATED COPY

> The following estimates are based on information we got from your tax form. You might be eligible for even more. To check for more benefits and to improve accuracy, review your information and answer a few more questions here.

**Comment by CalebPena** [comment]
I created the component for this, but the backend piece is not done yet, so the component is currently never rendered.

**Comment by sydney-devine** [comment]
@CalebPena can release, but I'm going to keep this open so that we know we need to re-test it once it renders

**Comment by sydney-devine** [comment]
@CalebPena we can release, but keeping this in the in review column for when we can actually test it.
