### ISSUE TITLE
Change header in results page for Lets Get Set Whitelabel

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#725]
Needs to eliminate reference to tax credits

suggested (please improve as you see fit): “XX programs with an estimated value of $YYYY monthly in cash or reduced expenses for you to consider.”

Subheader with path for additional info (suggested only):
 “This presumed eligibility was calculated based on your 2023 tax filing.  You can see if you qualify for XX additional benefits by providing additional information here.”

**Comment by sydney-devine** [comment]
@kbottagaro this is a dupe. I'm closing this
