### ISSUE TITLE
Create translation process for the ongoing benefits list we have on landing page

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#730]
From Rebecca.
We need an automated way that we can update the "Current List of Benefits" list that now residex on our landing page.
Our current english list of benefits is updated [here ](**https://docs.google.com/document/d/1WeINu3nJ_sRMVAd2jp2yRUWZjsgyqxLSHio9AUzRDqw?usp=drive_fs**)and pdf here: https://drive.google.com/file/d/1zMF0YevfxTjC8vYz6UypLtl7HnFQZOQe/view

I manually google translate each version and know there is a way we can automate this when we add several languages... would love your creative solutions!

**Comment by sydney-devine** [comment]
@kbottagaro closing this because it's not dev related. Addressing with website redesign
