### ISSUE TITLE
Edit "Partner with Us" to include/match assets from Get Started Guide

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#732]
contact: Kathleen.

Now that we have polished a "Get Started" guide for partners, we'd like to see this language reflected in our landing page.

At minimum, are there ways to provide available collateral to match what we've pupblished here?

https://drive.google.com/file/d/19ogZihJTiQ8xXqjUfc3WStJKc9qrAxoC/view

**Comment by kbottagaro** [comment]
@kbottagaro please add detail as you see fit!

**Comment by sydney-devine** [comment]
@kbottagaro This is a ticket for me. Antyhing on main website will be. Closing this ticket - can we take this over to email?
