### ISSUE TITLE
Update MFB Logo

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#733]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3836d569710aecf7f4a4a082b2bcd9dd417c5d63/MFB-Horizontal-reverse-nobk-highres.png)

**Comment by bespinosa01** [comment]
![MFB-Horizontal-reverse-nobk-highres](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/17464571/18950138-4067-4d94-9801-6d509facddec)

**Comment by sydney-devine** [comment]
@bespinosa01 heads up it's a white text logo which is why it might be showing weird as a file here. Lmk if any issues
