### ISSUE TITLE
Branding Updates: Results Page

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#748]
While we wait for the entire redesign, let's update:

- Add "YOUR RESULTS ARE IN!" - same details as #688
- Typography updates #734
- Highlight active tab in deep blue #293457
- Inactive tab color #E6E7E8
- Change the filter bar to deep blue #293457
- Change "Edit Screener Responses" button - maybe make it Mid blue like the add additional income/expense buttons? Open to ideas on this.

**Comment by rickyctd** [comment]
Carlos sent message to Sydney about blocker - need api key for google translation > will be difficult to complete this ticket without the api key.

**Comment by sydney-devine** [comment]
@rickyctd just responded to Carlos in slack. Apologies our team was out on Friday.
