### ISSUE TITLE
Update Styles Controller Colors

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-calculator#765]
Update `styleController.ts` with the new colors.

- [x] Update primary color
- [x] Update secondary color
- [x] Update confirmation background color ( update: removed )
- [x] Add color for primary background ( white, no need to add )
- [x] Add color for secondary background (light lavender ) 
- [x] Add color for cream

**Comment by CalebPena** [comment]
@Mdemenko1 I think that `#B85A27` is actually going to be our secondary color (in the issue, I previously had it as its own color).

**Comment by Mdemenko1** [comment]
> @Mdemenko1 I think that `#B85A27` is actually going to be our secondary color (in the issue, I previously had it as its own color).

@CalebPena @sydney-devine 
Could you help me to verify and confirm some colors?

primary color : #293457 (deep blue)
secondary color : #B85A27 (dark terra cotta)
confirmation background color: ?
primary background : ?
secondary background: ?
cream color: #F9EFE6 (cream) 

Also, @CalebPena 
Style controller has two objects with colors. Primary & secondary colors have different values in those. Do I need to update only default object or twoOneOne as well? If both, should I update them to the same values? What is twoOneOne is used for?

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/08b9c905-b151-4e0b-b620-9e0be39fd683)

**Comment by CalebPena** [comment]
@Mdemenko1 Confirmation background color can be removed. We are getting rid of that background on the confirmation page. Also, the primary background color is white, so I think we don't have to add that now. The secondary background color is the light purple. Don't update the `twoOneOne` primary or secondary colors. You can see our 211 branding [here](https://benefits-calculator-staging.herokuapp.com/step-1?referrer=211co) for context.
