### ISSUE TITLE
Headers Update

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#793]
When we changed the heading on the zip code page for Tell us where you live, it changed it for all the subsequent questions where the heading should still be Tell us about your household. Just now catching this issue.
Step 4, 6 & 7 should be "Tell us about your household" as the main heading.

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/119f62da-9f56-4401-bbde-07b54c2de810)

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/d03fce55-0311-4642-b3e0-6f3a983883ae)

**Comment by kbottagaro** [comment]
Change looks good.
