### ISSUE TITLE
As an administrator, I would like the ability to display a warning message on a benefit (example: if there is a localized delay or backlog within a county)

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#801]
Icon should be middle aligned with the text in the box. 
- Make icon red
- background: ECDEED
- 1 px border: #978398
- ignore the linked text in the mockup. It's going to just be plain text. 

**Icon**
![Warning](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/6c6826ee-bb82-4b5a-bc57-06920998961f)

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/85ed0671-f72d-4532-9cb6-d4b9bbba3278)

**Comment by CalebPena** [comment]
Added the `warning` to program type. https://github.com/Gary-Community-Ventures/benefits-calculator/pull/902

**Comment by CalebPena** [comment]
Similar component in https://github.com/Gary-Community-Ventures/benefits-calculator/blob/main/src/Components/BackToScreen/BackToScreen.tsx

**Comment by sydney-devine** [comment]
@CalebPena add instructions on how to test this pls.

**Comment by CalebPena** [comment]
1. Go to http://localhost:8000/api/translations/admin/programs/
2. Click edit on one of the programs that you want to add a warning.
3. Click on the link that says "Warning"
4. Add warning message

FYI empty warnings will be an empty string.
