### ISSUE TITLE
Top of the page buttons - create new component

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#824]
https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen

Also remove the save my results from the header

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/1932a4e1-0cd6-497d-9ead-9a646dca9e55)

**Comment by sydney-devine** [comment]
@sydney-devine to update comp with the actual header (language + share buttons)

**Comment by ivonne-hernandez** [comment]
@sydney-devine can you please share the save svg icon with me that's on the `Save My Results` button? 

Since we don't have the `Print my results` functionality ready to implement on this ticket it'll only have the `Email` and `Text` my results sections.

**Comment by sydney-devine** [comment]
@ivonne-hernandez Here's the save icon

![Disk](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/94a9fb6d-7a9c-48c2-8bc0-40a828c1b72c)
