### ISSUE TITLE
Create updated header for results page

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#825]
Background Color: #ECDEED 
Background for # Programs Found: #293457
Text Color: #293457
Font: Roboto Slab for $ values | Open Sans for label underneath

https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/052015ac-d397-46ae-b64d-6c1ba64f0958)

**Comment by rickyctd** [comment]
There are some errors on this page in the backend that prevent this from displaying in local.

**Comment by sydney-devine** [comment]
@CalebPena ^ see Ricky's note about results page in local. Can we get this figured out for their team?

**Comment by rickyctd** [comment]
@sydney-devine @CalebPena I think @mexi-cano was able to figure it out on his local and working with the rest of our team to figure it out on their locals. They will probably reach out if additional help is needed. Might want consider seeing if this is a more systemic issue that should be documented/resolved for future devs though?

**Comment by Mdemenko1** [comment]
@sydney-devine maybe Background Color, should be #FBF9FC (secondaryBackgroundColor) ?

**Comment by sydney-devine** [comment]
> 

Agree. I think I grabbed the wrong hex code when I typed this. It should definitely be #FBF9FC - sorry about that.
