### ISSUE TITLE
Create component for benefit category headings

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#829]
- Icons to come for each benefit category
- Font color: #B85A27
- Typography: Roboto Slab (bold for the main heading, regular for the $ value)
- Right justify the dollar value. Dollar value should display total $ value of the benefit category

https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/4a121cfe-1823-464c-8eec-eeabc8edff52)

ICONS FOR CATEGORIES
Housing and Utilities
![MFB-app-icons_House](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/2d648fa7-6a65-4ee8-bd9f-1591bb8f70f1)

Health Care
![MFB-app-icons_Medicaid](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/89dcced8-fd04-4f78-8e0e-8b9261ede97e)

Food and Nutrition
![MFB-app-icons_Food](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/bb176515-7a2b-4e52-9b99-dd1d6d05d622)

Transportation
![Transportation](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/c43be13f-83bf-4446-9ef7-aec3da04cf10)

Cash Assistance
![Cash Assistance](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/f998ca43-6b5d-43ba-ae21-d4de35cd8dad)

Child Care, Youth, and Education
![Childcare Youth Ed](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/d1382871-dd1b-449f-901a-80e62f27e1d0)

Tax Credits
![Tax Credits](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/35985846-e1e2-461e-a496-712c141813be)

**Comment by myang1010** [comment]
Hi @sydney-devine , do we have more details about font size and names for each heading? Below is what I have right now. I temporarily placed a sample component into the result page, so we can get some idea of what it'll look like. 

<img width="355" alt="mock" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/fb96333a-de1f-4f8a-8872-b055dc6066be"> 

I'm using `fontSize: 1.25rem` for heading text and `2rem` for the icon.
The heading titles are different than[ the design doc](https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen) , and I'm using the language from design doc for now.

Thanks and please let me know.

**Comment by sydney-devine** [comment]
> Hi @sydney-devine , do we have more details about font size and names for each heading? Below is what I have right now. I temporarily placed a sample component into the result page, so we can get some idea of what it'll look like.
> 
> <img alt="mock" width="355" src="https://private-user-images.githubusercontent.com/29790405/297208381-fb96333a-de1f-4f8a-8872-b055dc6066be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTM5ODYsIm5iZiI6MTcwNTUxMzY4NiwicGF0aCI6Ii8yOTc5MDQwNS8yOTcyMDgzODEtZmI5NjMzM2EtZGUxZi00ZjhhLTg4NzItYjA1NWRjNjA2NmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlM2Y0MzFhMTFjODE2MTVlZGFjYzc0YjNkNDc0ZDQwMGNjNzViYjY2MzdlODJiNmM5MDM2ZjM2M2QwODQwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5vy16HbO8qTXk0G2P1b-Fme3jcV-WYYaHk38Xxfg7Ug">
> I'm using `fontSize: 1.25rem` for heading text and `2rem` for the icon. The heading titles are different than[ the design doc](https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen) , and I'm using the language from design doc for now.
> 
> Thanks and please let me know.

@myang1010 I'm on a loaner laptop this am and can't open my file for the design to check font size, but what you have there looks good to me! I can circle back with you on what the font size was in the design once I get my laptop later.

**Comment by myang1010** [comment]
> @myang1010 I'm on a loaner laptop this am and can't open my file for the design to check font size, but what you have there looks good to me! I can circle back with you on what the font size was in the design once I get my laptop later.

Thanks Sydney! Please also help double check the titles for the icons as well.

**Comment by sydney-devine** [comment]
@myang1010 You mean the category heading name? We should pull that from the list of categories which already exists so the name matches what's in the system. 

@CalebPena or @ivonne-hernandez can you provide where @myang1010 can reference the existing categories please?

**Comment by CalebPena** [comment]
You can find the category list [here](https://github.com/Gary-Community-Ventures/benefits-calculator/blob/main/src/Assets/BenefitCategoryLists/benefitCategories.tsx)

**Comment by CalebPena** [comment]
Also @Mdemenko1 is creating a function to calculate the total value based on the category.

**Comment by sydney-devine** [comment]
@myang1010 & @bespinosa01  The final 4 logos have been uploaded in the description portion of this issue.
