### ISSUE TITLE
Create component for long-term benefits cards

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#830]
https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/3a741c7e-6477-46a6-9693-7cbcd5798be6)

**Comment by mexi-cano** [comment]
@sydney-devine I want to confirm that the desktop version should have the numbers on the left for each program? 

Also, I don't think there are any icons saved for each program. Is that something that will be added on the backend? @CalebPena

**Comment by sydney-devine** [comment]
> @sydney-devine I want to confirm that the desktop version should have the numbers on the left for each program?
> 
> Also, I don't think there are any icons saved for each program. Is that something that will be added on the backend? @CalebPena

Oh thanks for checking on that - nope please ignore the numbers. It was Sofia delineating option 1 or 2 haha. No icon for the program either. The card itself should look like the SNAP card in option 1 .
