### ISSUE TITLE
Create component for near-term resources cards

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#832]
https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/screen/3a5b1212-62f7-4f89-8a3f-02ff27981461?fullscreen

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/194a0b9c-f32e-4c4c-a16c-5007a7b61ba8)

**Comment by mexi-cano** [comment]
The comp shows icons and a category heading (i.e. Food Resource). The `need` object doesn't have a concise category/type. I can write a function to determine the categories or is there another way to grab these? @CalebPena @sydney-devine

**Comment by sydney-devine** [comment]
> The comp shows icons and a category heading (i.e. Food Resource). The `need` object doesn't have a concise category/type. I can write a function to determine the categories or is there another way to grab these? @CalebPena @sydney-devine
> 
> <img alt="Screenshot 2024-02-01 at 2 29 49 PM" width="1661" src="https://private-user-images.githubusercontent.com/7133950/301624354-458ed733-24a9-4e5c-8e3e-00c8d410250c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTY2MzEsIm5iZiI6MTcwNjgxNjMzMSwicGF0aCI6Ii83MTMzOTUwLzMwMTYyNDM1NC00NThlZDczMy0yNGE5LTRlNWMtOGUzZS0wMGM4ZDQxMDI1MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTkzODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE2MGUyMTYyMmVmZGQ4NTg4ZWJmYzhlNTQ4MDAzZjYzYmQ2ODQzNDE0ZjljM2RiYWY2N2NmYjRlYjE5YTU3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hyirlb04YbudBv8N5eafp_waRzsmTVueio3ALJtcwoc">

Categories for the near term help programs come from this for what each is called: 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/dc26ecaa-9ba3-4854-a206-65e29a60ff3d)

**Comment by mexi-cano** [comment]
Thanks for the response! The issue is that those categories are hard-coded and not mapped to the resources results. I'll write a function that connects the two unless @CalebPena knows of a better way. 

There is also a mismatch of category headings. For the 'Food or groceries' option, the comp shows it should read 'Food Resource'. Is it ok to use what's in the screenshot you posted? Thanks! @sydney-devine
