### ISSUE TITLE
In results, provide path to connect users to their nearest Family Resource Center for assistance

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#836]
**Dependency**:  List of approved FRCs (Kathleen talking with Family Resource Center Association)

**Why**: many users - particularly those outside the metro area - may not have local resources available in MFB and may not have an easy path to be connected to immediate need resources (ex: diaper bank).

As we scale, we want to have a "best path" that someone could connect to to receive acute assistance near their location.

**Comment by kbottagaro** [comment]
@sydney-devine This should be more of a catchall resource like 211. Not all of the centers would have the ability to assist with all applications.  The concept is that if someone wants to talk to someone in their area about local resources, they could reach out to their local FRC. We would link to this map - https://www.cofamilycenters.org/centers-member-family-resource-centers/ - and people can search based on where they live. I want to circle back with the FRCA director about this but would first like your feedback about whether we can make something like this work.

**Comment by sydney-devine** [comment]
@kbottagaro I think we can, but I think it should be listed in the apply with assistance piece. Maybe it's a separate blurb in that box, but otherwise we have to think through redesigning that help button on the new results page again

**Comment by kbottagaro** [comment]
@sydney-devine Following up on conversation about adding family resource centers to other programs. Suggested language below:

Your local family resource center may be able to connect you to other resources and support services. Find a center near you here.   ["Here" should link to this map - https://maps.cofamilycenters.org/.]
