### ISSUE TITLE
Extend card to full width when one row

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-calculator#845]
Also, use rems for media query so that it works on 211.

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/62856626/75a8f429-144a-4cf2-b1c0-cd38dd8073c3)

**Comment by sydney-devine** [comment]
@CalebPena 

The icons are gone on mobile

<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d9d80e128b2dc84717e39f6d8426c172af49703/image.png" alt="image.png" />
