### ISSUE TITLE
Don't Show :?

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-calculator#872]
- Update the dynamic function so that the income type displays in parentheses after the question
- Remove the colon, and just have the "?" after the main question stem. Parenthetical should follow after the main question stem. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/62856626/49d1fff1-130e-457b-a64d-3c2cec7b50d3)

**Comment by rickyctd** [comment]
<img width="1257" alt="Screenshot 2024-01-24 at 2 51 28 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/130072805/32cca83b-7e43-44e5-8c29-62369d58f9b8">
