### ISSUE TITLE
Design Special Notice message box on benefit page

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#880]
https://github.com/Gary-Community-Ventures/benefits-calculator/issues/801

Would you be able to give your thoughts/draft up some kind of warning box or important message box on this page for if there is a delay in being able to get a benefit? It should be something like a box with a warning icon/messaging. Similar to (see second screenshot)

![image](https://github.com/Gary-Community-Ventures/benefits-api/assets/109622199/1e5344cf-cdf6-4913-ae19-6a6c359a4d53)

![image](https://github.com/Gary-Community-Ventures/benefits-api/assets/109622199/30256610-41c9-404f-bdda-3ca2789bb2cb)

**Comment by kc-accidental** [comment]
![Untitled_Artwork 4](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/01fac104-0b2e-4403-a1bb-e690eca5c2a9)

Thoughts on this design? I tried it with the current orange background and then tried a lavender. I think this type of notification could be overlooked because of the heavy use of the orange, but what are your thoughts?

**Comment by kc-accidental** [comment]
Lulz. Sorry for the accidental complete! T-T

**Comment by sydney-devine** [comment]
> ![Untitled_Artwork 4](https://private-user-images.githubusercontent.com/149400219/299766126-01fac104-0b2e-4403-a1bb-e690eca5c2a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMTAzNDksIm5iZiI6MTcwNjIxMDA0OSwicGF0aCI6Ii8xNDk0MDAyMTkvMjk5NzY2MTI2LTAxZmFjMTA0LTBiMmUtNDQwMy1hMWJiLWU2OTBlY2E1YzJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxOTE0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmRmNzAwNjE3ZjQ4ODFjNzQzZTVmZWM0YmIzMjE3MGVjY2UwMzNjOWZhOTFmNTk3MTYwYjMwNTAxZDAyNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SLCWrKP1s5C4xbvGXrwdvC1AaKGk3xd114tUnmWi4PE)
> 
> Thoughts on this design? I tried it with the current orange background and then tried a lavender. I think this type of notification could be overlooked because of the heavy use of the orange, but what are your thoughts? The user would see the notification opened on the page but would have the choice to close it.
> 
> @sydney-devine @rickyctd

Hey @kc-accidental 

I think we probably have to axe the accordion. General user feedback on the accordions have been less than ideal, and I think especially for an important message, 1 - we can limit characters on what we post & 2 - want the user to see the full note. 

I would probably lean lavender background with maybe enlarging the icon so it stands out more, and we could maybe use a bit of red text in bold **Important Notice** or something to that effect to draw attention to it. Can't use the orange unless it's with white text, it doesn't pass the contrast testing for accessibility. 

Let me know what you think?

**Comment by rickyctd** [comment]
I know it's probably not part of the branding overall, but typically warning messages universally are in red/pink or yellow (if background). I wonder if we could do that in this instance if it's really important for the user to see it?

**Comment by sydney-devine** [comment]
> I know it's probably not part of the branding overall, but typically warning messages universally are in red/pink or yellow (if background). I wonder if we could do that in this instance if it's really important for the user to see it?

I think that would be ok. What if we use the deep blue as a border around the box (or no border, would be interested in seeing both) and then we can make the icon standard red and the text standard red on white background

**Comment by kc-accidental** [comment]
Accordion noted!
I feel like red could be too severe it's the background/border- whenever such a color pops up, most would think a technical issue/restriction/bad news- instead of something helpful like the notification at hand. 
It might work with just the icon being red though.
I’ll go ahead and mockup the color suggestions you both mentioned and try out different icons to see how it looks and see what you guys think.

**Comment by kc-accidental** [comment]
https://www.figma.com/file/S5bGIKHv4AxANvKygj0Ein/Site-Redesign?type=design&node-id=330%3A500&mode=design&t=eSsIAAT8uShqpKQd-1

Here are the variations I made! The blues with the red failed the color accessibility test so I axed that combo and I tried out the notice label both in and outside of the box. The last 3 designs looked too cluttered with the icons so I took them out.
I'm leaning towards either design 6 or 9 but I'm happy to mix and match.
(Don't mind the spacing between the box and anything else!)

Thoughts?

**Comment by sydney-devine** [comment]
> https://www.figma.com/file/S5bGIKHv4AxANvKygj0Ein/Site-Redesign?type=design&node-id=330%3A500&mode=design&t=eSsIAAT8uShqpKQd-1
> 
> Here are the variations I made! The blues with the red failed the color accessibility test so I axed that combo and I tried out the notice label both in and outside of the box. The last 3 designs looked too cluttered with the icons so I took them out. I'm leaning towards either design 6 or 9 but I'm happy to mix and match. (Don't mind the spacing between the box and anything else!)
> 
> Thoughts? @rickyctd @sydney-devine

Thanks Sofia!

This one was a favorite on our end. Do you know if that lavender passed the contrast test with the black text? 

Can we play around with color for the icon a little? I feel like the purple on purple didn't stand out enough. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/ceb866cd-3931-4cf1-827f-b6d185604e3b)

**Comment by kc-accidental** [comment]
<img width="453" alt="Screenshot 2024-01-26 at 10 41 19 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/a6076dea-98c6-4034-b069-67c15c41b0de">

The purple/black did pass the test - since none of the other brand colors worked, I went for a red and found a good shade that passed the test. What do you think? Also wanted to know your thoughts on the icon itself. There were a few other choices within the options. Did you guys like this one the most?

**Comment by rickyctd** [comment]
I like the exclamation point, could we try one with a circle around it so it looks a little more modular and similar to the help/info tool tip icons further down? would also take up some of the trapped space between the icon and the left edge of the text

**Comment by sydney-devine** [comment]
> I like the exclamation point, could we try one with a circle around it so it looks a little more modular and similar to the help/info tool tip icons further down? would also take up some of the trapped space between the icon and the left edge of the text

Agree, and it looks good in red! 

Can we actually try with a triangle around instead of circle? The circle with exclamation is used for all of the error messages, so want to just switch it up so it isn't the same. I'm getting an icon made with the triangle and exclamation point since we have it in another location with a similar type message too.

**Comment by kc-accidental** [comment]
> I like the exclamation point, could we try one with a circle around it so it looks a little more modular and similar to the help/info tool tip icons further down? would also take up some of the trapped space between the icon and the left edge of the text

<img width="674" alt="Screenshot 2024-01-26 at 10 55 35 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/db995d27-7458-478d-bc80-a718d40e2b7e">

Hows this?

**Comment by sydney-devine** [comment]
> > I like the exclamation point, could we try one with a circle around it so it looks a little more modular and similar to the help/info tool tip icons further down? would also take up some of the trapped space between the icon and the left edge of the text
> 
> <img alt="Screenshot 2024-01-26 at 10 55 35 AM" width="674" src="https://private-user-images.githubusercontent.com/149400219/300051183-db995d27-7458-478d-bc80-a718d40e2b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODg1MjAsIm5iZiI6MTcwNjI4ODIyMCwicGF0aCI6Ii8xNDk0MDAyMTkvMzAwMDUxMTgzLWRiOTk1ZDI3LTc0NTgtNDc4ZC1iYzgwLWE3MThkNDBlMmI3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNjU3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjYzNjMzMmMwYWM4MTkxZjNkYjdkYWMzZjliNTJlMDE4ZTI0MDMyZDVhNjgxYWI2OTYwMTY2MGQwMjFjNWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vdmdBehEtKl8xAI98GwAOwmGnPHzXcbSfiq8qyIuL5I">
> Hows this?

That was so fast haha. See my note above re triangle exclamation point. Otherwise, I think it looks good. @rickyctd?

**Comment by kc-accidental** [comment]
<img width="781" alt="Screenshot 2024-01-26 at 11 00 58 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/bf3eba3e-12ba-4b80-833c-ed5327481cd1">


Figma has plugins for icon libraries!

**Comment by rickyctd** [comment]
love it

**Comment by sydney-devine** [comment]
Same - one clarifying piece. Assume that the message might be 3-5 lines sometimes, are you thinking the icon is top aligned with the first line, or center aligned with text?

**Comment by sydney-devine** [comment]
> > Same - one clarifying piece. Assume that the message might be 3-5 lines sometimes, are you thinking the icon is top aligned with the first line, or center aligned with text?
> 
> <img alt="Screenshot 2024-01-26 at 11 09 43 AM" width="1121" src="https://private-user-images.githubusercontent.com/149400219/300054437-2ee04508-edfa-46d3-9411-0b349135d714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODk0ODQsIm5iZiI6MTcwNjI4OTE4NCwicGF0aCI6Ii8xNDk0MDAyMTkvMzAwMDU0NDM3LTJlZTA0NTA4LWVkZmEtNDZkMy05NDExLTBiMzQ5MTM1ZDcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNzEzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGYwYTBiYjg3MDk1OTNmMTc0ZTA3YmFjYzgyNjczYTZiZGM1NDk5NGI2ODk5YzU3MDY4YzI5Y2QxNzA4ZGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8pmG1ezQb3pZlcO4aa-TTBDdhTr0xBxXM-EScBKeB50">
> I think it would be best centered to avoid awkward negative space.

Agree - can I please have a final screenshot of just the centered with the 3 line text pls?

**Comment by sydney-devine** [comment]
> <img alt="Frame 11" width="360" src="https://private-user-images.githubusercontent.com/149400219/300055534-88259747-d423-46f3-8998-9bacb5715c9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODk3MjksIm5iZiI6MTcwNjI4OTQyOSwicGF0aCI6Ii8xNDk0MDAyMTkvMzAwMDU1NTM0LTg4MjU5NzQ3LWQ0MjMtNDZmMy04OTk4LTliYWNiNTcxNWM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNzE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjUwZTdkZTZjNTVlY2YxYjg2YjdhNTQ0YmZjNGJmN2QyMGE3MDI2Njc2ZjRmZjM3NTRhNzhhOGM1NzNkYzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L3pmaR7dSZgrQI0HIulPfqefW4fiHWckODbEdByyvtk">
> Here you go!

Ack sorry that ask was not specific. . . can I have it with the rest of the mockup so team can see where to position please?

**Comment by kc-accidental** [comment]
<img width="433" alt="_          4" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/26de25db-b5ec-43c9-a419-6ac3f6198b87">

No prob! Here you are.

**Comment by sydney-devine** [comment]
> <img alt="_ 4" width="433" src="https://private-user-images.githubusercontent.com/149400219/300056570-26de25db-b5ec-43c9-a419-6ac3f6198b87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTAwMDIsIm5iZiI6MTcwNjI4OTcwMiwicGF0aCI6Ii8xNDk0MDAyMTkvMzAwMDU2NTcwLTI2ZGUyNWRiLWI1ZWMtNDNjOS1hNDE5LTZhYzNmNjE5OGI4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNzIxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWJjZjE1ODAxNTVlMDhiZGFkYzhiNTc3ZmIwYjJiZWY1YzMzMTk4MDg5YTFmNDdkYjcyMzZmNjU4Yzg5Y2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ryhj-9Vd1KhQc8Br6RJ6o59mDWhn8dmElWhJjOT67j4">
> No prob! Here you are.

Thank you!!
