### ISSUE TITLE
Design "Low confidence" flag for benefits page

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#884]
"Low Confidence" on the card

Similar to the "New Benefit" flag - https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen

we want a different flag that says "Low Confidence" This will be used for benefits where we cannot reach 90% accuracy (just due to nature of the screener and not having enough information) for the value/eligibility rules. 

Let's play around with color on this flag?

**Comment by rickyctd** [comment]
@kc-accidental additional context, the example screens shows what a current flag for new benefit looks like. We want a different flag for low confidence. Also take into account that some benefit(s) may have BOTH flags.

**Comment by kc-accidental** [comment]
<img width="437" alt="Screenshot 2024-02-12 at 1 18 59 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/2dabb7f4-f861-4ac7-ad26-158c29f60798">
Thoughts on the color combos?
@sydney-devine @rickyctd

**Comment by rickyctd** [comment]
I think I'm partial to the gray. Red seems too scary. Orange kind of blends in. Blue looks like a button. 

Maybe also slightly more space in front of the text when next to "new benefit"

**Comment by kc-accidental** [comment]
> I think I'm partial to the gray. Red seems too scary. Orange kind of blends in. Blue looks like a button.
> 
> Maybe also slightly more space in front of the text when next to "new benefit"

Noted on the spacing!
<img width="502" alt="Screenshot 2024-02-12 at 1 34 45 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/149400219/b01e45c8-94d5-470d-9988-cb4e66eed36f">

**Comment by sydney-devine** [comment]
> > I think I'm partial to the gray. Red seems too scary. Orange kind of blends in. Blue looks like a button.
> > Maybe also slightly more space in front of the text when next to "new benefit"
> 
> Noted on the spacing! <img alt="Screenshot 2024-02-12 at 1 34 45 PM" width="502" src="https://private-user-images.githubusercontent.com/149400219/304203157-b01e45c8-94d5-470d-9988-cb4e66eed36f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzExMzIsIm5iZiI6MTcwNzc3MDgzMiwicGF0aCI6Ii8xNDk0MDAyMTkvMzA0MjAzMTU3LWIwMWU0NWM4LTk0ZDUtNDcwZC05OTg4LWNiNGU2NmVlZDM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQyMDQ3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZhZjM2Nzc5NTNkNzg0YTYzYjdiN2E1ZTdiN2Y1ZDhjYTY1YTU5MDllYjQ5OTY1Nzg0YzQ2NmZhNjcyYmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DreTz2f-xa0uDzlxwZ5EW-x2tqqY_l1xeX4mQ8EnuVI">

I love how they look next to each other. I'm currently mostly partial to grey, but worried it won't stand out enough on its own. Agree that red looks scary and what @rickyctd said re orange and blue.
