### ISSUE TITLE
Create White Label for Get Ahead Colorado

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#892]
Create white labeled version for "Get Ahead Colorado"
- Add "Get Ahead Colorado" to referral drop down
- referrer code: getaheadco ? let me know if that works
- Cobranded logo 

![Get Ahead CO MFB Cobranded Logo Horizontal](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/fae73e5a-4242-46d4-b96b-7416e0e1c82f)

**Comment by ivonne-hernandez** [comment]
@sydney-devine Does `gac` work for the referrer code?

**Comment by sydney-devine** [comment]
> @sydney-devine Does `gac` work for the referrer code?

Works for me!
