### ISSUE TITLE
Results Page Update: Benefits Cards

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#922]
**Desktop: It looks like the title of the benefit is in black. Can we make this deep blue? #293457**

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/284f6bfd-d51c-468a-ad4b-6f8af9db4c9c)

**Mobile: Looks like all of the text is black**

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/d5cd98a5-b8e7-447e-ae69-9d81025a4384)

**Mobile (mostly) - let's middle align the "More Info" button to the title text so there isn't so much white space under the button**

<img width="400" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/96a7a783-19ec-4ff5-beec-87718517f623">

**"More Info" button needs a hover - let's do an inverse on the hover. White background, blue border, blue text**

**Looks like "Application Time" for SNAP on desktop view is on one line, but for all the other ones it's 2 lines?**

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/3976f6e6-56c4-45b4-a96c-0f7640d6250c)

**Comment by rickyctd** [comment]
@sydney-devine for "Looks like "Application Time" for SNAP on desktop view is on one line, but for all the other ones it's 2 lines?"

can you show an example of what you WANT it to look like? What do the other programs look like? screenshot please? thank you! :)

**Comment by sydney-devine** [comment]
> @sydney-devine for "Looks like "Application Time" for SNAP on desktop view is on one line, but for all the other ones it's 2 lines?"
> 
> can you show an example of what you WANT it to look like? What do the other programs look like? screenshot please? thank you! :)

All the others have 2 lines
![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/f114eb03-0272-4552-b8b5-1f1163dee32c)

**Comment by rickyctd** [comment]
Thanks @sydney-devine that screenshot does bring more clarity. Could you also include one with the full width so we can see the whole thing in context just like the screenshot for FNS?

**Comment by sydney-devine** [comment]
> Thanks @sydney-devine that screenshot does bring more clarity. Could you also include one with the full width so we can see the whole thing in context just like the screenshot for FNS?

https://benefits-calculator-staging.herokuapp.com/c3f94a7e-40b4-4df2-aa5c-f732571877ea/results/benefits

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/3e3e779e-50ae-4db1-b5c4-132573063893)

**Comment by rickyctd** [comment]
@sydney-devine Thank you! This is really helpful. I am noticing that "estimated savings" may be looking at a similar issue with Medicaid have things on 2 lines of text and the others not. Are we going to be expecting changes to that added to this ticket? We want to make sure that the scope of the ticket is correct and not have to adjust the scope and points too much later. Would be great to consider minimum criteria for the upcoming sprint to see if we need to split this one and have some be taken care of later, or else we can see about @Mdemenko1 taking on fewer tickets.

**Comment by sydney-devine** [comment]
> @sydney-devine Thank you! This is really helpful. I am noticing that "estimated savings" may be looking at a similar issue with Medicaid have things on 2 lines of text and the others not. Are we going to be expecting changes to that added to this ticket? We want to make sure that the scope of the ticket is correct and not have to adjust the scope and points too much later. Would be great to consider minimum criteria for the upcoming sprint to see if we need to split this one and have some be taken care of later, or else we can see about @Mdemenko1 taking on fewer tickets.

Whoops. Did not notice that. I would say let's make that match application and have it be two lines.
