### ISSUE TITLE
Results Page Updates: Tabs on Mobile

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#924]
Let's make the tabs slightly shorter on mobile so they don't take up so much height/space on the screen. We can probably cut the padding top/bottom by close to 50%. 

<img width="413" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/c75eba86-5995-4558-981a-b84134124fba">

**Comment by mexi-cano** [comment]
@sydney-devine The tabs are currently rectangular shaped. I have reduced the padding by 50%. Screenshots below for review:

original:
![Screenshot 2024-02-13 at 5 06 40 PM](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/7133950/5d9e845b-0619-4e19-ab88-333b382a30dc)

updated:
![Screenshot 2024-02-13 at 5 06 19 PM](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/7133950/7f67e52f-cb77-4539-9593-659b6c2ccc77)

**Comment by sydney-devine** [comment]
> @sydney-devine The tabs are currently rectangular shaped. I have reduced the padding by 50%. Screenshots below for review:
> 
> original: ![Screenshot 2024-02-13 at 5 06 40 PM](https://private-user-images.githubusercontent.com/7133950/304561682-5d9e845b-0619-4e19-ab88-333b382a30dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MzQzNzMsIm5iZiI6MTcwNzkzNDA3MywicGF0aCI6Ii83MTMzOTUwLzMwNDU2MTY4Mi01ZDllODQ1Yi0wNjE5LTRlMTktYWI4OC0zMzNiMzgyYTMwZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTgwNzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYyMDYwZjY5OGJiMzg4NDQ3YTI4NWI0ZTMyZWVlZDFkZGNmM2FiNzcxNDE4MTEzNGI4MzkyZjMzYjI1ZDMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fH7JMWRj4L78MvO_p_1VzHybpQLYIByJdFNpywXPN5o)
> 
> updated: ![Screenshot 2024-02-13 at 5 06 19 PM](https://private-user-images.githubusercontent.com/7133950/304561691-7f67e52f-cb77-4539-9593-659b6c2ccc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MzQzNzMsIm5iZiI6MTcwNzkzNDA3MywicGF0aCI6Ii83MTMzOTUwLzMwNDU2MTY5MS03ZjY3ZTUyZi1jYjc3LTQ1MzktOTU5My02NTliNmMyY2NjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTgwNzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWZiNmVjMjVhNmZjYzQyNTA3NjgwNTE5YTI4YTViYWMzMThiOGU2ZGFlYTVjYWZiYjY0ZTQ1NDQ0NGFhYWU1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1dh1huNh4vnLM5DS2B1n4CIHzkjhDffP56oErKJXBPY)

Looks much better for mobile - TY!

@CalebPena @ivonne-hernandez just an FYI since we were just looking at full page this am
