### ISSUE TITLE
Results Page Final Edits

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#945]
- Calculations on headings and benefits cards need to be per month. They're displaying annual value right now. 
- Edits (did this live) on program page
- Program page: move estimated values box to the right of the name of benefits box
- Program page: Make get help applying boxk documents box wider on desktop + paragraph wider
- Program page desktop: smallest font should be 16, go up from there for rest of headings. 
- Fix near term benefit cards accordion
- Padding under 2-1-1 button (between button & footer)

**Comment by ivonne-hernandez** [comment]
- Remove the 211 text and button from the 211 site.
- Update 211 svg icons to the red color.
