### ISSUE TITLE
Standardize design system

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#947]
App font sizing standards, colors, etc.

**Comment by sydney-devine** [comment]
[My Friend Ben Brand Guide_v3.pdf](https://github.com/Gary-Community-Ventures/benefits-calculator/files/14285023/My.Friend.Ben.Brand.Guide_v3.pdf)

**Comment by kc-accidental** [comment]
@sydney-devine @rickyctd Wanted to clarify - the system would be for both web and mobile or just web?

**Comment by rickyctd** [comment]
probably both? We would want both eventually. I think just a matter of if we want it all on one ticket or split.

**Comment by sydney-devine** [comment]
> probably both? We would want both eventually. I think just a matter of if we want it all on one ticket or split.

Agree. I kinda think we should just do both at the same time, even if this spans a longer sprint for you.

**Comment by kc-accidental** [comment]
> > probably both? We would want both eventually. I think just a matter of if we want it all on one ticket or split.
> 
> Agree. I kinda think we should just do both at the same time, even if this spans a longer sprint for you.

Ok cool! Can I get the current version of the mobile mockup (for reference) along with screen size dimensions used for it?

**Comment by sydney-devine** [comment]
> > > probably both? We would want both eventually. I think just a matter of if we want it all on one ticket or split.
> > 
> > 
> > Agree. I kinda think we should just do both at the same time, even if this spans a longer sprint for you.
> 
> Ok cool! Can I get the current version of the mobile mockup (for reference) along with screen size dimensions used for it?

https://xd.adobe.com/view/9c25b118-90b5-409e-b9b6-36662f2b59c2-c976/?fullscreen

Here's the results mockup. 

Not 100% sure the screen dimensions used.
