### ISSUE TITLE
Results Page: Final Edits V2

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#955]
CHANGE LIST - Must be ready for release 2/21. 

- [x] Program page name showing the abbreviated name vs full name. Fix wrapping on mobile & desktop. for full name. See @ivonne-hernandez screenshotbelow. 

<img width="1310" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/8a6a7430-beab-4090-af6d-7ff14a588ef7">

- [x] Fix media query gap for main results header from 700 - 775

<img width="721" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/30229293-e7eb-43ef-8ee1-35b7fbc2abb0">

- [x] Backend new benefits flag

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/9b6d789b-fcb3-4e4d-b237-462549df93bf)

- [x] Update curve of tabs to 1 rem

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/3152a006-2d94-440f-a906-ba40517e4d4a)

- [x] Near term help cards. . . 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/cc8cddc8-1915-4b4e-800b-4397d107748a)

- [x] Fix Child Care Category value so that we have the braided/capped amount 

- [x] ADD Childcare braiding blurb. Copy: `This monthly value is an estimate of the combined average value of child care and preschool programs. Savings from programs may overlap.` Background is the light lavender, font is the deep blue. 

<img width="929" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/7a3dfdba-a14a-4a2a-aecb-2baea5a647c1">

- [x] LGS Blurb at the top of the page. Add back in. @CalebPena 

WISH LIST FIXES. DO IF WE HAVE TIME

- [x] Can we update this so the heading only splits into 2 lines if the category name is too long?

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/0e7ed862-1188-4743-9336-52301b5acfda)

**Comment by ivonne-hernandez** [comment]
This is the program heading on mobile:
<img width="503" alt="Screenshot 2024-02-16 at 12 49 46 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/24553e54-f71a-413a-92c1-60c345199881">

**Comment by sydney-devine** [comment]
@CalebPena Tax Credit in header is not calculating. Showing $0 even though there are benefits showing below. 
<img width="833" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/2c262e4b-e1d2-443c-96c2-100d21b77961">

<img width="1313" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/78db470c-d7fb-458c-b0b1-c3be2fc8da6c">

**Comment by sydney-devine** [comment]
@CalebPena 

LGS Results page showing annual value at the top
https://benefits-calculator-staging.herokuapp.com/6fdfc61f-dcdc-4947-91c8-4f0e78ef07cd/results/benefits

**Comment by sydney-devine** [comment]
@CalebPena @ivonne-hernandez 

2-1-1 Update icon color to red. Update new benefit flag issue. 

<img width="914" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/8cdcefc9-d71e-4069-8557-6e803b566e86">
