### ISSUE TITLE
Add "twice a month" option to dropdown menu for question "How often are you paid this income"

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#977]
Add "twice a month" option to dropdown menu for question "How often are you paid this income"

See related ticket for help text - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/978.

NOTE: Someone who gets paid twice a month on the same dates each month gets 24 paychecks over 12 months. Someone who gets paid every other week gets 26 paychecks over 12 months.

**Comment by kbottagaro** [comment]
@CalebPena I see this in the current sprint and thought it was going to be part of today's releases. Can we include this in the April 12 releases? This is important to Salud.

**Comment by rickyctd** [comment]
@kbottagaro @CalebPena to clarify what needs to be done for this ticket, is it to solely add the "twice a month" option on the drop down? The original ticket text links to 978 which doesn't appear to have been done either. The original text on this ticket also includes a "note" and it is unclear if that is meant to be a note internally to clarify for us or if it needed to be displayed. If it needs to be displayed, it does not indicate how you'd like that displayed.

**Comment by rickyctd** [comment]
@Mdemenko1 I just clarified with @CalebPena and this ticket is just to add the option on the drop down and not adding the note or help text on display. That will be the separate ticket for next week.

**Comment by kbottagaro** [comment]
Hi, Ricky. Thanks for asking for clarification. Ticket 977 involves adding
the "twice a month" option to the income frequency dropdown menu. I assume
that this change involves updating the backend calculations to reflect this
method of income reporting. As a nontech person, I had thought the updated
calculation would be implied in the ticket - but please let me know if you
need a separate ticket for that.

And yes, ticket 978 is related. The help text would be displayed like the
other help text bubbles we added last week with question marks.

Please let me know if you need further clarification. So appreciate your
help!

**Comment by kbottagaro** [comment]
Seems like our messages crossed. I understand from Caleb the calculations
are updated on the backend because MFB had twice a month when it was first
created.

I also understand the help text will be a separate ticket for next week.

**Comment by rickyctd** [comment]
@kbottagaro Thanks so much for the context and clarification!
