### ISSUE TITLE
Add help text to dropdown income options for “every 2 weeks” and “twice a month”

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-calculator#978]
Add help text to dropdown income options for “every 2 weeks” and “twice a month”:

If user chooses "every 2 weeks": This means you get paid every other week.
If user chooses "twice a month": This means you get paid twice a month on the same dates each month. 

Help bubble goes with "How often are you paid this income" question on income block

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/180e5705-9977-498a-965e-e0a9aa7f5384)

See related ticket that adds "twice a month" as an option - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/977.

**Comment by ivonne-hernandez** [comment]
@sydney-devine Can we close this one out since it's already done under this other issue: https://github.com/Gary-Community-Ventures/benefits-calculator/issues/977 ?

**Comment by sydney-devine** [comment]
@ivonne-hernandez this one is for adding the help text that goes along with the "How often are you paid this income" question. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/55ef473a-8522-4b29-8b76-89983a40edcf)

**Comment by ivonne-hernandez** [comment]
@sydney-devine for this ticket do we only want the help bubble to appear when the user selects every two weeks or twice a month? Or do we just want to display it regardless?

**Comment by sydney-devine** [comment]
@ivonne-hernandez display regardless. It's there so people can always see it because no one knows the dif between the two.

**Comment by kbottagaro** [comment]
@sydney-devine I'm seeing this under the ? for how often someone gets paid. Looks good to me - ok with what you wanted?

**Comment by sydney-devine** [comment]
@kbottagaro Yup - I just moved to approved
