### ISSUE TITLE
Update tax value $ amount to include the comma on results

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#980]
<img width="1373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2E3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3015399ff120d882c74a4e920a6514814f73ee9/image.png" alt="image.png" />

**Comment by kbottagaro** [comment]
@CalebPena Looks good.
