### ISSUE TITLE
Copy of Create NC Zip options 

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#982]
To support migration of region to django admin we need to begin to compile NC specific objects/data.

relates to:
https://github.com/Gary-Community-Ventures/benefits-api/issues/267

**Comment by bespinosa01** [comment]
https://www.unitedstateszipcodes.org/nc/

**Comment by msrezaie** [comment]
The free (personal) version of zip codes database csv [file](https://www.unitedstateszipcodes.org/zip_code_database.csv?download_auth=0e6367ad88e64b63a10c0f2c87a263da) from [UnitedStatesZipCodes.org](https://www.unitedstateszipcodes.org/nc/) does not include overlapping counties on any of the zip code instances. On the enterprise version of the database however, everything is included. The attached 'counties by zip codes' JSON file for the state of NC does not include overlapping counties on each of the zip codes.

Compiled NC specific zip codes: [countiesByZipCodes.json](https://github.com/Gary-Community-Ventures/benefits-calculator/files/14593140/countiesByZipCodes.json)

I was able to save the JSON data in the `Configuration` model, and test it locally. 

`/api/configuration/` endpoint:
![Screenshot 2024-03-13 154442](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/79583632/964c4d05-8838-44e0-aaa7-e8b50ca95181)

**Comment by msrezaie** [comment]
Refer to the following doc for compiled NC specific data

[nc-config](https://docs.google.com/document/d/1v4UeK1CkO8pHVym8ghCKftietVX_sMddznVnZTR3TbQ/edit#heading=h.myou3cgy72h1)

**Comment by msrezaie** [comment]
@laurenbriskin this is the ticket for the entirety of NC specific configuration data. You can view the so far compiled data in here [nc-config](https://docs.google.com/document/d/1v4UeK1CkO8pHVym8ghCKftietVX_sMddznVnZTR3TbQ/edit#heading=h.myou3cgy72h1)

I am currently using the following sources to gather and compile NC counties by zip codes the appropriate config format for our backend api to consume:
https://www.unitedstateszipcodes.org/
https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt
