### ISSUE TITLE
Research: Current workflow for state modifiers in federal programs

### ISSUE THREAD

**Issue by bespinosa01** [Gary-Community-Ventures/benefits-calculator#984]
Currently all federal programs i.e. WIC, SNAP. Run through Policy Engine. The codebase currently has some state specific modifiers hardcoded. The goal is to identify those modifiers and propose configureable solution. 

Potential Key Files: 
`programs/programs/policyengine/policy_engine.py`
`programs/programs/policyengine/calculators/programs/member.py`
`screener/views.py`

**Comment by rickyctd** [comment]
@msrezaie put Google doc with research notes here please: https://drive.google.com/drive/u/0/folders/12b05xvPkzzbDgqdhsPiNvdWGj_L6I0jg

**Comment by msrezaie** [comment]
https://github.com/Gary-Community-Ventures/benefits-api/pull/318
