### ISSUE TITLE
Add message if a member of the household is not in the tax unit

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-calculator#993]
Backend needs to add flag.
Frontend needs to add message.

- Needs a flag for every tax benefit. Backend will flag individuals who are not in the tax unit. 
- Need to do this for Pell Grant too

**Comment by kbottagaro** [comment]
language a HH will see when applicable: 

There may be members of your household who are not part of your "tax household." Ask them to complete this tool to determine if they qualify for this benefit.

**Comment by sydney-devine** [comment]
@kbottagaro @CalebPena where are we imagining this language goes?

**Comment by kbottagaro** [comment]
Deferring to Caleb on this - not sure how he was thinking this should be
displayed.

**Comment by sydney-devine** [comment]
The display should match the other warning message display. @kbottagaro we need the copy for what will go here. Something along the lines of, It looks like you entered household members that are not part of your tax unit. . . etc. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/ee7c4370-0a17-44e9-b769-d0db19b01f58)

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena I thought this was the language we're using: 

There may be members of your household who are not part of your "tax household." Ask them to complete this tool to determine if they qualify for this benefit.

**Comment by sydney-devine** [comment]
> @sydney-devine @CalebPena I thought this was the language we're using:
> 
> There may be members of your household who are not part of your "tax household." Ask them to complete this tool to determine if they qualify for this benefit.

Oh I'm so sorry I'm dumb and just missed that. TY!

**Comment by kbottagaro** [comment]
As per @CalebPena, note will also appear for RTD LiVE.

**Comment by kbottagaro** [comment]
As per @CalebPena, note will also appear for RTD LiVE.

**Comment by sydney-devine** [comment]
> *

Great!

**Comment by kbottagaro** [comment]
Also as per @CalebPena - include flag for these:
Medicaid (Health First Colorado)
SSI
CHP+
OAP
ANDCS

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena I don't see this message in staging - ?
